### ISSUE TITLE
One-Page Scroll for the website

### ISSUE THREAD

**Issue by anindya** [sugarlabs/www-sugarlabs#10]
As of now, the website is using a very primitive UI. I think that the data on every page can be compressed down and put into something more elegant like one-page scroll. Something like this www.thepetedesign.com/demos/onepage_scroll_demo.html

**Comment by samdroid-apps** [comment]
Sorry, I'm not 100% sure what you mean in this ticket.  You seem to talk about 2 separate things:

1.  Compressing the content down:  content suggestions are always welcome.  I think that the home page is pretty compressed and that we need more extra content (eg. getting started guides), but if you want to work on the home page feel free to!
2.  Using the funny scrolling things:  trends pass by faster than the wind.  While one page scroll is elegant now, if you go to the breading ground of html trends (aka. yc hacker news), you will see a comment complaining about the scrolljacking that these sites do.  I fear that you have missed the boat on that trend, and would be using it as more of a clique than anything else.  Maybe find newer trends, or just create a usable design.

**Comment by walterbender** [comment]
scrolljacking is a terrible UI experience and since we are not beholden to advertisers, no reason to do it.

**Comment by davelab6** [comment]
@walterbender I suggest closing this issue if you won't accept any pull request to implement this, no matter how well crafted :)

**Comment by davelab6** [comment]
@anindya thanks for posting this - I think its a fun idea but perhaps the same intent of separating each section of the homepage can be done with CSS (use of color and element positioning) rather than JavaScript

**Comment by walterbender** [comment]
@davelab6 Seems to be two different ideas expressed here: how to represent the page(s) internally and how to interact with the page. I'd like to let the former play out.

**Comment by davelab6** [comment]
@walterbender ok :) 

@anindya , could you explain more what you meant by 

> I think that the data on every page can be compressed down

**Comment by anindya** [comment]
@davelab6 I think I wrote that for the amount of content. Content on every page is very, content can be cut down to bare bones, just to show the crux of what we want to say on every page. 
Also, 1 year after opening the issue, I also feel that scrolljacking is not the way to go.

**Comment by davelab6** [comment]
I agree the content needs work, and to address this I've made a information architecture plan, https://github.com/sugarlabs/www-sugarlabs/blob/master/STRUCTURE.md

Since you now think scrolljacking is not ideal, I'll close this :) 

Thanks for participating :)
