### ISSUE TITLE
Bug in calculator

### ISSUE THREAD

**Issue by sahran99** [sugarlabs/www-sugarlabs#100]
When I type in a function, there is no output when I press equal. I am on Version 62.0.3202.94 (Official Build) (64-bit) of google chrome. In addition, there is no history for the previous calculations that I have done. 
![image](https://user-images.githubusercontent.com/34138005/33445941-199e3e04-d5c4-11e7-8a38-1d3b7ebed66e.png)
![image](https://user-images.githubusercontent.com/34138005/33445947-1e5d9c78-d5c4-11e7-9980-780a8de3a618.png)

**Comment by quozl** [comment]
That's not part of the site.

See [Calculate.activity](https://github.com/llaske/sugarizer/tree/master/activities/Calculate.activity) for the source and issue tracking.
