### ISSUE TITLE
navigation bar shifts to the left when on mobile 

### ISSUE THREAD

**Issue by stasiekq** [sugarlabs/www-sugarlabs#101]
Hi,
I'm here from google code-in. Everything in your website's code seems good, the look of the page is also perfect. But when I opened the website on my mobile, I noticed a few responsivity bugs. When I tapped the screen, defects disappeared, as i expected. I'm pretty sure that it's just a singular bug, but if you recieved more messages about that, better check it out. I attach the screenshot where you can see this bug.
![screenshot53](https://user-images.githubusercontent.com/34140561/33450823-57ecc06a-d60d-11e7-9985-6df0621a336d.jpg)

**Comment by Hrishi1999** [comment]
Seems to be a browser specific issue (safari?).
