### ISSUE TITLE
Problem On Translation Page Mobile View

### ISSUE THREAD

**Issue by thesolark** [sugarlabs/www-sugarlabs#103]
![77f0dbae-9255-479a-b3aa-9927efdbe1d7](https://user-images.githubusercontent.com/34140160/33453349-f781b3d2-d61d-11e7-97aa-f3aa67ac67df.jpeg)
When opening the translation language page on my mobile device, the left-hand column has content overlapping, making it hard to read, while the right-hand column looks okay.

**Comment by quozl** [comment]
Not part of this repository.   No work is planned on the translation system.
