### ISSUE TITLE
lagging animations on weaker devices

### ISSUE THREAD

**Issue by stasiekq** [sugarlabs/www-sugarlabs#110]
Hi,
Your website looks great now, I can't say anything bad about it. But when I visited the page on my old pc, with intel celeron and 1 gb ram, used non stop for 8 years, when I scroll the website, all the animations are going on, my monitor stuters,and that annoyed me. If I were in your shoes, I would make another version of website for weaker devices, with less number of smooth animations.

**Comment by abdulsamad234** [comment]
Nice idea, basically making another version of the site that can run on old devices?

**Comment by quozl** [comment]
You're both new here, or you would have already been aware of previous discussions about performance ... we have over 2.6 million laptops deployed with Sugar desktop integrated, many with a Browse activity that has a link to Sugar Labs web site.  Performance of the site on old hardware is important to some of us; and anything you can do to fix it will be welcome.

But a more correct way to handle this is with a continuous integration that tests each pull request against browser CPU demand.
