### ISSUE TITLE
Top bar animation isn't very smooth

### ISSUE THREAD

**Issue by NickDim** [sugarlabs/www-sugarlabs#111]

**Comment by walterbender** [comment]
Can you please tell us more about the problem and also the environment in which you tested?

**Comment by NickDim** [comment]
I used google chrome and when scrolling down the header's animation was very rough.

**Comment by NickDim** [comment]
I just mean maybe adding more frames to the animation would help because when you scroll, there isn't really much of an animation, the header kind of just pops up in a larger size.

**Comment by quozl** [comment]
Adding more frames to the animation will increase the CPU demand on the client.
