### ISSUE TITLE
broken link in https://sugarlabs.org/about-us/

### ISSUE THREAD

**Issue by capucinecoudert** [sugarlabs/www-sugarlabs#114]
[Dextrose] points to [https://sugardextrose.org/] wich is broken.

**Comment by yashagrawal3** [comment]
@walterbender should I just point it to Dextrose wiki page until broken URL  [https://sugardextrose.org/] 
 problem is not resolved?

**Comment by quozl** [comment]
It should be removed, as it is no longer current.
