### ISSUE TITLE
Suggestion on page https://sugarlabs.org/about-us/

### ISSUE THREAD

**Issue by capucinecoudert** [sugarlabs/www-sugarlabs#115]
"Harmonic distribution" and "Replacing Textbooks" are pointing to DEPRECATED and OBSOLETE pages, wich is confusing for the user.

**Comment by quozl** [comment]
How are deprecated or obsolete pages confusing?  It seems quite clear what they mean.

These links should be removed, as the projects that they linked to are no longer current.
