### ISSUE TITLE
Stopwatch Activity confusion

### ISSUE THREAD

**Issue by khreate** [sugarlabs/www-sugarlabs#120]
Consider adding tooltips to the button elements in the Stopwatch Activity 
![sugarproblems](https://user-images.githubusercontent.com/26176077/33509051-137883c6-d6c4-11e7-8e38-a16ab0376609.JPG)

as these symbols may be confusing or foreign to some users.

**Comment by quozl** [comment]
That's not part of the site.

See [Stopwatch.activity](https://github.com/llaske/sugarizer/tree/master/activities/Stopwatch.activity) for the source and issue tracking.

See also tooltips in the Python activity; https://github.com/sugarlabs/stopwatch
