### ISSUE TITLE
Social Help Page Button 

### ISSUE THREAD

**Issue by gracepfohl** [sugarlabs/www-sugarlabs#123]
The Social Help Page button at the bottom of the home page should have more space above and below it. Also, I don't think a button is needed here. A hyperlink would blend in with the rest of the page better.

**Comment by walterbender** [comment]
Perhaps "Join the Conversation" should be the button.

**Comment by gracepfohl** [comment]
I like that! It seems friendlier and justifies the use of the button more!

**Comment by yashagrawal3** [comment]
where should "Join the Conversation" button redirect to? 
[IAEP mailing list page](http://lists.sugarlabs.org/listinfo/iaep) ?

**Comment by quozl** [comment]
Social Help hasn't got traction; almost nobody will answer there, so I don't think it should be linked.

IAEP has people who will answer, but it has old-style e-mail only user-experience on Mailman 2.  Newer web-based user-experience in Mailman 3 is Postorious.  systems@ mailing list can be involved if a move to that stack is contemplated.

Meanwhile, linking to IAEP is adequate but not the best option.

**Comment by yashagrawal3** [comment]
why don't we work on moving the stack to Postorious? 
For the time being, adding a button pointing to IAEP.

**Comment by quozl** [comment]
To drive that process, write to systems@ mailing list.

**Comment by yashagrawal3** [comment]
It has been many days but I still haven't got a confirmation email for subscription on the Systems mailing list. Please, anyone, look into it.

**Comment by quozl** [comment]
I've no access.  Write to scg@sugarlabs.org, the list administrator, and copy Walter Bender.

**Comment by scanterog** [comment]
Done.

**Comment by pro-panda** [comment]
Fixed in #139
