### ISSUE TITLE
Suggestion: Add spacing after the list elements

### ISSUE THREAD

**Issue by LTSENG01** [sugarlabs/www-sugarlabs#127]
On the testimonial carousel in the Principles section of the About Us page, add spacing after the list element numbers. 

Ex.) Make it `1. Regular reports...` instead of `1.Regular reports...`. (Add spacing after the `1.`)

<img width="1260" alt="screen shot 2017-12-01 at 9 23 24 pm" src="https://user-images.githubusercontent.com/5864947/33510744-04b941c6-d6de-11e7-93a9-95f4a10ed378.png">

Safari 11.0.1 on macOS 10.13.1

**Comment by Swayamsvk** [comment]
Added a pull request for this.

**Comment by quozl** [comment]
Thanks, but I don't think this needs to be fixed.  The issue was created during GCI 2017 as part of a task, but had not been reviewed.  The original source of the text is an old and unmaintained Wiki page https://wiki.sugarlabs.org/go/Sugar_Labs
