### ISSUE TITLE
Visual Bug: Scrolled Down Navigation Bar has uneven vertical spacing

### ISSUE THREAD

**Issue by Vigasaurus** [sugarlabs/www-sugarlabs#129]
The Nav Bar Entries skew upwards, when on Desktop the page is scrolled down. 
![uneven vertical nav bar spacing](https://user-images.githubusercontent.com/19434157/33510950-a21f7a1c-d6d8-11e7-96fd-0737cb39670a.png)

**Comment by kipply** [comment]
Issue exists, thanks!

**Comment by Swayamsvk** [comment]
I think this issue is solved please close this issue.
