### ISSUE TITLE
Suggestion: Sugarizer Page is really empty

### ISSUE THREAD

**Issue by Vigasaurus** [sugarlabs/www-sugarlabs#131]
It could use some reassuring for users that they are on the correct page in the form of a banner or some images
![sugarizer blandness](https://user-images.githubusercontent.com/19434157/33510968-dd0eb566-d6d8-11e7-909c-224fb7d804d7.png)

**Comment by Hrishi1999** [comment]
Hello, Sugarizer is something different, and is not based on the website. It actually is web-version of sugar os. The button styles and everything else matches the style of sugar. The placeholder text won't mean nothing here as the input type doesn't have any fixed format, we are just taking user name here. However, some changes are necessary for better accessibility.

You can report sugarizer issues here : https://github.com/llaske/sugarizer

**Comment by quozl** [comment]
User is not prepared in advance for Sugarizer and is confounded by the experience.  That's a problem with www.sugarlabs.org reported by this issue.

**Comment by samswag** [comment]
@quozl ?? could you explain more?

**Comment by quozl** [comment]
@samswag, sure.  Consider a naive user, someone who knows nothing about Sugar or Sugarizer.  Our contestants in GCI 2017 are good examples, but there are other people like this that we would not hear about.  When they visit www.sugarlabs.org they arrive with certain expectations, and then when they click on the "Try" button they are given something they don't understand and don't know how to react.  A kind of cognitive dissonance.  We can fix that by preparing them for what they are about to experience.

We could also promote global training in how to use a browser Back button, but that's less likely to solve the problem.
