### ISSUE TITLE
Visual Bug: Extra space between top paragraph and horizontal line in goals page

### ISSUE THREAD

**Issue by Vigasaurus** [sugarlabs/www-sugarlabs#133]
The Horizontal line could be centered, or the space below the paragraph reduced. 
![horizontal line](https://user-images.githubusercontent.com/19434157/33510980-162055d0-d6d9-11e7-9cca-86e513d39834.png)

**Comment by Swayamsvk** [comment]
I think this issue is solved please close this issue.
