### ISSUE TITLE
Suggestion: The "get sugar" menu item shouldn't be a drop down

### ISSUE THREAD

**Issue by Vigasaurus** [sugarlabs/www-sugarlabs#136]
This becomes really cramped on smaller screens, or mobile at times. 
Maybe include a page with descriptions of each download type, with separate instructions. 
![downloads](https://user-images.githubusercontent.com/19434157/33511069-3a2848e2-d6da-11e7-8286-87015840a0b8.png)

**Comment by Hrishi1999** [comment]
IMO, it should be like this. The user stays on the same page instead of going to another page.
