### ISSUE TITLE
Site preview link on README.md broken

### ISSUE THREAD

**Issue by Ploypiti** [sugarlabs/www-sugarlabs#140]
The link marked as the live version of the redesigned site is broken, returned error 404.
https://geekrypter.github.io/sugarLabsWebsiteRedesign/

**Comment by quozl** [comment]
Parts of 725368d3bc881bf70b9bf84cf4d5a878426f1035 that affected README.md should be reverted.  We need a volunteer to do that.  Problem is that the commit included pull-request or project specific details that were temporary.
