### ISSUE TITLE
GCI 2017 - Improvements 

### ISSUE THREAD

**Issue by rmrf1039** [sugarlabs/www-sugarlabs#143]
Improvements: 
<img width="1680" alt="screen shot 2017-12-03 at 3 02 36 am" src="https://user-images.githubusercontent.com/33394453/33518857-3ddc553e-d7d7-11e7-8d2f-3c0c394ec038.png">

<img width="1680" alt="screen shot 2017-12-03 at 3 10 54 am" src="https://user-images.githubusercontent.com/33394453/33518962-7ca99f78-d7d8-11e7-8a5b-addadeec309f.png">
<img width="1680" alt="screen shot 2017-12-03 at 3 11 15 am" src="https://user-images.githubusercontent.com/33394453/33518963-7ec7283e-d7d8-11e7-96a5-3ddf4018783d.png">
<img width="1680" alt="screen shot 2017-12-03 at 3 15 30 am" src="https://user-images.githubusercontent.com/33394453/33518964-7eec0d20-d7d8-11e7-8a8a-a0591dd135e9.png">
<img width="1680" alt="screen shot 2017-12-03 at 3 30 44 am" src="https://user-images.githubusercontent.com/33394453/33519078-82aea718-d7da-11e7-9662-430f61b03366.png">

**Comment by walterbender** [comment]
Please break this up into separate issues for each bug. And please add a brief text description of the problem for each issue, along with an appropriate title.

**Comment by lalitmee** [comment]
@walterbender Are these issues solved or not?

**Comment by walterbender** [comment]
I don't believe so.
