### ISSUE TITLE
Titles on footer don't contrast well with background color

### ISSUE THREAD

**Issue by khreate** [sugarlabs/www-sugarlabs#145]
![readability](https://user-images.githubusercontent.com/26176077/33521649-c7649eae-d79d-11e7-8a9e-93a1bc846185.JPG)

As seen in the picture, the titles for "Sugar Labs", "Development", and "Resources" are difficult to read. Consider using a lighter color (a lighter grey, perhaps) to create more contrast, increasing readability.

**Comment by khreate** [comment]
Also, when these labels are hovered over, the cursor becomes activated. Not sure if this was intentional as they are not linked to anything.

**Comment by pg07codes** [comment]
i cant reproduce this issue. If it has been fixed, please close the issue.

**Comment by Pro-Panda** [comment]
While the contrast has been fixed, the cursor still becomes activated. The issue has been partially fixed

**Comment by FiberesimaJoseph** [comment]
Why not change the font color of the text i think the background is okay if the font colors are changed
