### ISSUE TITLE
List of IRC on Introduction to IRC is showing an element closer

### ISSUE THREAD

**Issue by khreate** [sugarlabs/www-sugarlabs#146]
![sugarteam_closeelement](https://user-images.githubusercontent.com/26176077/33521979-cd30dc90-d7a6-11e7-9c9a-9c816b13b3b1.JPG)

The #ubuntu-sugarteam/li>  contains /li>, assuming not intentional

**Comment by khreate** [comment]
Just made sure on inspect element, /li> is typed twice, once inside of the list element and once in the element closer (</li>)

**Comment by walterbender** [comment]
We should cull a few of these as they are obsolete:
dextrose, mitml, olpc-admin, olpc-au, treehouse, treehouse-es
