### ISSUE TITLE
On Google Chrome, bug and suggestion for top menu bar

### ISSUE THREAD

**Issue by eqsmy** [sugarlabs/www-sugarlabs#147]
On the website, the menu bar on the top shows the logo, but the logo stays the same size and doesn't shrink the same way it does in Safari. 

**Safari**
<img width="880" alt="screen shot 2017-12-02 at 7 26 38 pm" src="https://user-images.githubusercontent.com/34151362/33522026-3a09afbe-d797-11e7-8aa0-ef7d4cfef47e.png">
<img width="871" alt="screen shot 2017-12-02 at 7 26 31 pm" src="https://user-images.githubusercontent.com/34151362/33522034-5a5009b2-d797-11e7-96be-6bc86f99d45c.png">

**versus Chrome**
<img width="411" alt="screen shot 2017-12-02 at 7 26 04 pm" src="https://user-images.githubusercontent.com/34151362/33522030-494d8ec8-d797-11e7-8820-7658312f860c.png">

Also, when the menu button is clicked in the top left corner, the font color is too similar to the background, making it difficult to read unless highlighted. The social media links also cover the side menu. 
<img width="342" alt="screen shot 2017-12-02 at 7 25 49 pm" src="https://user-images.githubusercontent.com/34151362/33522036-73411722-d797-11e7-8340-67a30e428903.png">

**Comment by pg07codes** [comment]
cant reproduce this issue. is it fixed ?

**Comment by abhijain2003** [comment]
I don't think this error exist in google chrome

**Comment by quozl** [comment]
Thanks for testing.
