### ISSUE TITLE
Front Page Video Not playing

### ISSUE THREAD

**Issue by MrMalfunction** [sugarlabs/www-sugarlabs#148]
![image](https://user-images.githubusercontent.com/24508987/33523042-8bccb108-d822-11e7-94f9-541842349ebf.png)
See the video is not playing so maybe you should change the video format.
I am using Mozilla Quantum 32bit[beta channel] .

**Comment by quozl** [comment]
I saw this also with Firefox-57.0.1 on 64-bit Ubuntu 16.04.
