### ISSUE TITLE
Mobile View Issue+ Suggested Solution

### ISSUE THREAD

**Issue by MrMalfunction** [sugarlabs/www-sugarlabs#149]
![image](https://user-images.githubusercontent.com/24508987/33523075-7b9c3c58-d823-11e7-898c-6b330799925f.png)
That's a lot of space user might wait for something to appear there.
Solution decrease the width between to the two elements.

**Comment by samswag** [comment]
Thanks for the update

**Comment by MrMalfunction** [comment]
I will keep Updating.

**Comment by quozl** [comment]
Is also an issue on Firefox-57 on desktop, so I'll reopen.

**Comment by avinashbharti97** [comment]
@quozl  @samswag  @MrMalfunction 

should it look like this?


![after_padding_change](https://user-images.githubusercontent.com/22724583/37400725-d1235846-27ab-11e8-82e5-5a6eb1343bc8.png)

**Comment by quozl** [comment]
In general, vertical distance should be consistent between the elements.

In particular for this issue, it is the distance from the three dots down to the "Have a taste".

In comparison, consider the distance;
* from the "Try now!" down to the background colour change.
* from the background colour change down to "GET SUGAR",
* from each background colour change on the page up or down to the next element.

Is also an issue on Firefox-58.0.4 on desktop.

**Comment by quozl** [comment]
@avinashbharti97, https://github.com/sugarlabs/www-sugarlabs/pull/209 didn't seem to make any difference for Firefox on desktop.

**Comment by avinashbharti97** [comment]
@quozl changes were reflected in firefox when i was checking on local server, However i will check again

**Comment by quozl** [comment]
Yes, I checked on a freshly installed laptop with no cache.  Perhaps the distance has reduced a little bit.

**Comment by avinashbharti97** [comment]
okay i will check again, thanks for information
