### ISSUE TITLE
Need Some Improvements

### ISSUE THREAD

**Issue by PreVizsla** [sugarlabs/www-sugarlabs#152]
First, pls change the website appearances when we click the Try now button. At first i thought the websites crashed and just show a pure white screen with a name box. And pls make more ez to navigate around the website. Second, i suggest that we can do/access the search engine on the main page not on a new web page. Lastly, give more instruction and quick tips for new people how to use this websites feature.

**Comment by quozl** [comment]
Perhaps being dumped into Sugarizer without explanation is both discoverable _and_ irritating.  I suggest removing the link, or linking to the Sugarizer main page rather than the Sugarizer try now page.
