### ISSUE TITLE
GCI Suggestions - spacing and colors

### ISSUE THREAD

**Issue by cweckle** [sugarlabs/www-sugarlabs#154]
**1. Change aesthetic spacing**
In the following photo, the spacing isn't even between objects, which makes the layout look a bit messy. In the first picture, there should be a space between the email address box and the subscribe button. 
<img width="352" alt="screen shot 2017-12-03 at 7 33 41 am" src="https://user-images.githubusercontent.com/34151362/33526898-6fb4c5f8-d7fc-11e7-9cb3-c5250cc124df.png">

In the second picture, there should be a space before the social help page button. 
<img width="823" alt="screen shot 2017-12-03 at 7 33 35 am" src="https://user-images.githubusercontent.com/34151362/33526901-724a9e14-d7fc-11e7-9084-94e1cf40e51d.png">

In the third picture, there should be a space between the button and the dots that dictate what slide the user is on. There is plenty of space between the logo and the button, so if the buttons were just moved up to be midway between the dots and the logo, that would be better. 
<img width="936" alt="screen shot 2017-12-03 at 7 32 35 am" src="https://user-images.githubusercontent.com/34151362/33526902-7684ff38-d7fc-11e7-81bf-b1d4a0376123.png">

**2. Change color of online chat button**
When scrolling through white backgrounds, it is very difficult to see the "Chat on our IRC channel" button in the bottom right. I didn't even see the button until I got to the bottom of the page. If the color was changed to a contrasting color, it would be much more visible.
<img width="1230" alt="screen shot 2017-12-03 at 7 33 00 am" src="https://user-images.githubusercontent.com/34151362/33526957-4d89c2f2-d7fd-11e7-970c-5c7855d812d7.png">

**Comment by Hrishi1999** [comment]
@samswag @walterbender the recent merges seem to have broken the header and the top background image. Need to check

**Comment by quozl** [comment]
Needs better testing before merge.

**Comment by quozl** [comment]
Since fixed.
