### ISSUE TITLE
Navbar broken

### ISSUE THREAD

**Issue by Indmind** [sugarlabs/www-sugarlabs#158]
navbar broken if viewport width is smaller than 991px and bigger than 768px on desktop, tested on chrome ubuntu

![images](https://user-images.githubusercontent.com/29256127/33538562-9318b344-d8f4-11e7-8e24-806cdc1b28dc.png)

**Comment by sanatankc** [comment]
Yeah that and also footer

![screen shot 2017-12-04 at 11 34 41 am](https://user-images.githubusercontent.com/20373641/33538389-21d703aa-d8e7-11e7-9b84-cc3a80f8c7fb.png)

Don't know why, must have broken due to some pull. It was fine earlier.

**Comment by quozl** [comment]
@sanatankc, this is an opportunity for you to learn "git bisect" to find which commit caused it.

**Comment by sanatankc** [comment]
It is happening after merging pull request #109
