### ISSUE TITLE
Search Bar Improvement

### ISSUE THREAD

**Issue by g30r93g** [sugarlabs/www-sugarlabs#161]
Consider integrating the search bar into the search button. For example, when the user's cursor hovers over the button, a search bar appears and takes you to the current search page with all the search results.
![33514693-690466b6-d750-11e7-83eb-5f5f3e03bf6c](https://user-images.githubusercontent.com/31825917/33567818-5b490496-d91c-11e7-9bfc-9a820c6e421a.jpg)

**Comment by abdulsamad234** [comment]
Nice idea

**Comment by yashagrawal3** [comment]
@quozl I am trying to implement this. My changes in sass files are not reflecting on the localhost. Please help.

**Comment by quozl** [comment]
I'm not familiar with the software stack used, you'd best ask someone else.  My best guess is for you to follow https://github.com/sugarlabs/www-sugarlabs/blob/master/README.md or find out from the source what process step uses the sass files.

**Comment by nathan-jacob** [comment]
@quozl Shouldn't this issue be closed with the movement of the search bar at sugarlabs.org from the bottom of the page to the header?

**Comment by quozl** [comment]
Yes, thanks.
