### ISSUE TITLE
Re-order Tab Bar

### ISSUE THREAD

**Issue by g30r93g** [sugarlabs/www-sugarlabs#162]
The tab bar is well integrated but it would look better if the dropdown menus were on the right and the non-dropdown menus were on the left.
Recommended Order: Search, About, Use, Try Now, Download, Get Sugar, Join Us, Blog

**Comment by lalitmee** [comment]
@walterbender Should we change the order of the Tab Bar? I think the current order is also fine.

**Comment by walterbender** [comment]
I see no reason to change it: "better" was not explained.
