### ISSUE TITLE
About Page - Moving Cards

### ISSUE THREAD

**Issue by g30r93g** [sugarlabs/www-sugarlabs#163]
The cards start moving before the user scrolls to see them. They should only start moving when the user has scrolled to that part of the page. A user may experience this if they were 
too slow when moving down.
![33514750-3fd22eda-d751-11e7-8643-75b4f2cf3fd9](https://user-images.githubusercontent.com/31825917/33567988-d40f0880-d91c-11e7-974f-ed4cd506ac3c.jpg)

**Comment by akshat-vashistha** [comment]
can I still contribute on this issue @g30r93g ? I would be more than interested to work on it.

**Comment by chimosky** [comment]
@akshat-vashistha please make your changes and open a PR if you have a fix. Thanks!

**Comment by quozl** [comment]
This would be better forwarded upstream, and may have already been fixed there so an update of the theme may help.  Still, the work is not planned, so I'll close the issue for the moment.
