### ISSUE TITLE
Hyperlinks - Improvement

### ISSUE THREAD

**Issue by g30r93g** [sugarlabs/www-sugarlabs#165]
Give each link a rounded box similar to the goals page. This will say to the user that there is something to interact with. Another bonus is that there is a design theme that can be seen throughout the website.

**Comment by kushagra189** [comment]
@g30r93g  can you please elaborate the issue if it is still unassigned.

**Comment by S-kus** [comment]
I would like to work on this. @g30r93g Can you explain a bit more?

**Comment by chimosky** [comment]
Thanks for indicating interest @S-kus, I'm closing this as it's stale and the person who opened it seem to have abandoned the issue.

**Comment by S-kus** [comment]
Thanks, @chimosky, please, let me know if there is anything else where I can contribute.

**Comment by chimosky** [comment]
> Thanks, @chimosky, please, let me know if there is anything else where I can contribute.

I'm guessing you recently subscribed to our mailing list and I'd sent a developer how-to so it'll be easier for you to know what part of Sugar Labs you can contribute to based on your skill-set/interests, I don't know your skill-set and can't make any recommendations so if can share your skill-set then I can make recommendations.

**Comment by S-kus** [comment]
Okay. Thank you @chimosky I will mail you regarding it.

**Comment by quozl** [comment]
Also list for yourself what you want to learn.

See [Eric Raymond's How To Become A Hacker](http://www.catb.org/~esr/faqs/hacker-howto.html) for some ideas on progression in open source communities.  Many of us began this way.

**Comment by S-kus** [comment]
Thank you @quozl. I will go through it.
