### ISSUE TITLE
 Contribute to website button - suggestion

### ISSUE THREAD

**Issue by julianvdhogen** [sugarlabs/www-sugarlabs#167]
You could make the github contribute text a button or edit it to not be blue but the same color as the rest of the text and make it more in the middle of the rest of the text at the side.
![knipsel](https://user-images.githubusercontent.com/10560914/33657257-04d1d896-da79-11e7-9f83-901618aa15c5.PNG)

**Comment by mann27** [comment]
I would like to take up this issue.

**Comment by Pro-Panda** [comment]
Hi @mann27,

You need not ask for permission to take up an issue. You should check for pull requests linked to the issue. If there are none, feel free to make a pull request.

Please see our guide to [contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing)

**Comment by quozl** [comment]
My opinion is that the colour can stay as it is; it nicely reinforces the open nature of the site.  This issue was raised by a participant during Google Code-in, as part of the competition, and nobody else has expressed agreement until now.

**Comment by mann27** [comment]
Hello @Pro-Panda 

Thanks for the guidance so @quozl should i work on this issue or not and also can you please send an link of sugar-labs channel on Gitter or Slack .

**Comment by quozl** [comment]
@mann27, thanks for your interest.  Our competition of ideas occurs at pull-request stage, not issue stage.  Issues are used to track potential future work.

You can work on this issue if you like; with the knowledge that at least one person thinks it **isn't** worth doing, and that one person thinks it **is** worth doing.  We can't and shouldn't stop you.  When your pull-request is made, people will use [our guide for reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers) to assess your work and decide whether to merge.  Read that guide to see what we will be looking at.

You can also work on changes that have no issue at all.  Something that _you_ think needs to be fixed.

I don't know of any contributors using Gitter or Slack.  We do use IRC, and have quite a few contributors willing to use it.  See network Freenode, channel #sugar.  If you don't have an IRC client program, see http://meeting.sugarlabs.org/ click through to #sugar and then join.  I don't think this issue or your work yet needs that kind of communication, but you might have other questions to ask.
