### ISSUE TITLE
Intro video - suggestion

### ISSUE THREAD

**Issue by julianvdhogen** [sugarlabs/www-sugarlabs#168]
The intro video is a little smaller then the video frame and that makes it with blackborders maybe it would look nicer withouth that black borders.
![k2nipsel](https://user-images.githubusercontent.com/10560914/33657459-b76ee94e-da79-11e7-9de1-ad0cc7a3e0c5.PNG)

**Comment by quozl** [comment]
There is no longer a video.

**Comment by julianvdhogen** [comment]
Hi, Thanks for your respons. i would put you on itwould like to point out that this is a git issues report over 5 years old I would like to stop receiving emails regarding old reports. Thank you for your understanding and I wish you a nice day.Verstuurd vanaf mijn iPhoneOp 4 feb. 2023 om 00:34 heeft James Cameron ***@***.***> het volgende geschreven:﻿
Closed #168 as completed.

**Comment by quozl** [comment]
Thanks for writing.  Sorry, there's nothing much I can do about the mails.  The mails arise from GitHub and your profile notification settings.  You can turn off notifications there, or look for old issues and click on the unsubscribe button.

It is also our fault as an organisation for asking for issues to be created during Google Code-In and yet not doing anything with the issues.
