### ISSUE TITLE
Menu dubble down arrow - Bug

### ISSUE THREAD

**Issue by julianvdhogen** [sugarlabs/www-sugarlabs#169]
i think i found a bug! the menu at the blog side has to arrows down sometimes is more of a glitch.
![knipasel](https://user-images.githubusercontent.com/10560914/33657682-4dbef63c-da7a-11e7-8d7e-770d7cd6884a.PNG)

**Comment by Hrishi1999** [comment]
I am experiencing this with all of them. Thanks for reporting.
