### ISSUE TITLE
Social buttons float over sidebar - bug [GCI]

### ISSUE THREAD

**Issue by TheLukaszNs** [sugarlabs/www-sugarlabs#170]
I think that I found a bug - when You are on device which screen width is smaller or **equals 1260px**, the social media buttons start to float over opened sidebar, so You can't even see the text of some sections.
It  disappears when the screen width is smaller than **1236px**.
![gci1](https://user-images.githubusercontent.com/25536472/33675711-d2e040da-dab3-11e7-9e83-bd925aee5679.png)

**Comment by amaaniqbal** [comment]
I fixed this way back and I guess it can be closed.
