### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#18]
Why is this site licensed under CC-BY-NC? That means this is not a "free work" per https://creativecommons.org/freeworks/ :(

**Comment by davelab6** [comment]
Ping :)

**Comment by walterbender** [comment]
The "old" website was CC-by-Attribution 3.0. Not sure when/why the switch
was made.

On Wed, Apr 20, 2016 at 11:43 AM, Dave Crossland <notifications@github.com>
wrote:

> Ping :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sugarlabs/www-sugarlabs/issues/18#issuecomment-212483299>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by davelab6** [comment]
BY or BY-SA would be great!

**Comment by davelab6** [comment]
In fact I see the https://github.com/sugarlabs/www-sugarlabs/blob/master/LICENSE file contains the GPLv3.... Looking at https://github.com/sugarlabs/www-sugarlabs/graphs/contributors it seems there are 6 contributors: 2 have trivial patches that are probably not subject to copyright - https://github.com/sugarlabs/www-sugarlabs/commit/808085eb3948399cc4237e490e010380ae4e00b1 and https://github.com/sugarlabs/www-sugarlabs/commit/81d79770da4d2a4363de8bf4665833018cee5e82 - and then @shadowninjazx contributed some photos and a page in https://github.com/sugarlabs/www-sugarlabs/commit/ab0533a474e569a504d45675bc3b94ed75ebef73 - and then @tradzik and @samdroid-apps and @walterbender have everything else. 

I'm reasonably sure that these are all the copyright holders. 

So, if you 4 can agree on CC-BY-SA for content and GPLv3 for JS, by commenting on this issue, I'll make a PR to clarify this in the files.

**Comment by walterbender** [comment]
OK with me.

On Thu, Apr 21, 2016 at 11:40 AM, Dave Crossland <notifications@github.com>
wrote:

> In fact I see the
> https://github.com/sugarlabs/www-sugarlabs/blob/master/LICENSE file
> contains the GPLv3.... Looking at
> https://github.com/sugarlabs/www-sugarlabs/graphs/contributors it seems
> there are 6 contributors: 2 have trivial patches that are probably not
> subject to copyright - 808085e
> <https://github.com/sugarlabs/www-sugarlabs/commit/808085eb3948399cc4237e490e010380ae4e00b1>
> and 81d7977
> <https://github.com/sugarlabs/www-sugarlabs/commit/81d79770da4d2a4363de8bf4665833018cee5e82>
> - and then @shadowninjazx <https://github.com/shadowninjazx> contributed
> some photos and a page in ab0533a
> <https://github.com/sugarlabs/www-sugarlabs/commit/ab0533a474e569a504d45675bc3b94ed75ebef73>
> - and then @tradzik <https://github.com/tradzik> and @samdroid-apps
> <https://github.com/samdroid-apps> and @walterbender
> <https://github.com/walterbender> have everything else.
>
> I'm reasonably sure that these are all the copyright holders.
>
> So, if you 4 can agree on CC-BY-SA for content and GPLv3 for JS, by
> commenting on this issue, I'll make a PR to clarify this in the files.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sugarlabs/www-sugarlabs/issues/18#issuecomment-212978255>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by samdroid-apps** [comment]
Hello,

So the JS is already under AGPLv3+.  https://github.com/sugarlabs/www-sugarlabs/commit/115dd7a52f8712b21346ce0f0e158cc397a5ebd3  AGPL is the GPL, but the idea of "distributing software" includes putting it up on a web server for the public.  It's the GPL of the web.

At the bottom of the site, it says "Created by the Sugar Labs community, available under the CC BY NC 4.".  I can't full remember why that was choose (it is not a fully free license!!!), but I think that it is the same one as the old site, which we probably used parts of (directive work??).

Any work to clarify the situation is appreciated.

**Comment by davelab6** [comment]
If you have a doubt about reaching all the copyright holders, then I
suggest we throw the whole thing away and start with something that is
cleanly licensed.

AGPL is useful for server-side code, so clientside JS under AGPL doesn't
make sense.

**Comment by samdroid-apps** [comment]
Well, AGPL does no harm vs GPL.  Don't worry mate, I've already done the license for that.

**Comment by davelab6** [comment]
>  AGPL does no harm vs GPL

It may strain our relationship with sponsors who accept GPL but not AGPL.

**Comment by davelab6** [comment]
@tradzik and @shadowninjazx please comment :)

**Comment by shadowninjazx** [comment]
@davelab6 Sorry for being late. I agree on the CC license of the pictures I uploaded.

**Comment by davelab6** [comment]
@shadowninjazx thanks!

@tradzik what do you think?

**Comment by quozl** [comment]
Stale, closing.
