### ISSUE TITLE
Projects Thumbnails Suggestion

### ISSUE THREAD

**Issue by lalitmee** [sugarlabs/www-sugarlabs#183]
In the about us page, in the projects section, it would be more expressive if we can have thumbnails or cards types of projects description. Somewhat like in the gif below.

![divi-thumbnail-border](https://user-images.githubusercontent.com/10762218/33958481-85ced90c-e06a-11e7-92e2-375d157af809.gif)

**Comment by manan-goel-1999** [comment]
Can I work on this?

**Comment by samswag** [comment]
Go on.

**Comment by VatsalBatra** [comment]
@samswag  i would like to work on this issue.

**Comment by samswag** [comment]
Sure go on .

**Comment by VatsalBatra** [comment]
@samswag can you provide/suggest any suitable /official logo for MATH4 PROJECT and sugar creation  kit ,can't find any suitable one or should i submit the code with these pic only
![about-us project](https://user-images.githubusercontent.com/20797544/37877965-c732cca4-307f-11e8-9def-8f5f9a27044a.png)

**Comment by quozl** [comment]
The projects section were mostly placeholders.

Only two are current, SoaS and GSoC.  The Sugar Creation Kit is obsolete.  The Math4Team has been inactive for many years.  We have two short term development [projects](https://github.com/orgs/sugarlabs/projects) in the GitHub organisation, and several potential projects inside GSoC.

Use some sort of generic logo if you must.

In my opinion, the section does not need logos.  While it would be more expressive, the cost of maintaining logos is high.  Your difficulty finding logos is indicative of that cost.
