### ISSUE TITLE
An automate process using gulp

### ISSUE THREAD

**Issue by sanatankc** [sugarlabs/www-sugarlabs#189]
This has been mentioned before.
@kipply mentioned it in #121,
@quozl also mentioned in a comment in #159 

It is hard to make changes in current setup. First we have to make change in source file then minify it is using a minifer. Everyone is using different minifier.

It would be really good if we could have some sort of process using gulp (or grunt).

**Comment by kanishkarj** [comment]
Hey! I would like to work on that.

**Comment by quozl** [comment]
@kanishkarj, any progress?  This is still causing workflow trouble.
