### ISSUE TITLE
Search fails on pages other than index.html

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#193]
## reproducer

* open https://sugarlabs.org/sugar-for-raspberry-pi/
* try search

## observed result

* `404 not found` with URL of `https://sugarlabs.org/sugar-for-raspberry-pi//search/?q=raspbian`

## expected result

* search results

**Comment by kushagra189** [comment]
I would like to claim this issue

**Comment by kushagra189** [comment]
@quozl  can you just brief me up on this?

**Comment by quozl** [comment]
@kushagra189, no, I've said pretty much everything about the problem already.  I've not dug into the source code to diagnose the problem.  If I had continued further I would have fixed the problem myself rather than share it for someone else to fix.  If you have specific questions please ask.

**Comment by kushagra189** [comment]
@quozl  please look into this pull request #196

**Comment by quozl** [comment]
@kushagra189, the problem still occurs with ce2be43, please investigate and explain.

**Comment by kushagra189** [comment]
@quozl  working on it.

**Comment by abdulsamad234** [comment]
I could help with the issue

**Comment by abdulsamad234** [comment]
I think it would help if we just change the line 42 of nav.html from:
`document.getElementById("searchLink").href = window.location.href + "/search/?q=" + re;`
to:
`document.getElementById("searchLink").href = 'https://sugarlabs.org/' + "/search/?q=" + re;`

**Comment by quozl** [comment]
Thanks.

I see you've made an orphaned or unlinked pull request in
https://github.com/sugarlabs/www-sugarlabs/pull/198 that correlates to your suggestion above.  This introduces a new problem; search would not work unless the site was running on https://sugarlabs.org/ ... should you instead process `window.location.href` to keep only the method, delimiters, and server host, stripping the path?

Also, the issue is now wider; shall we revert ce2be43?

**Comment by abdulsamad234** [comment]
Okay, i'll work on that and link to the pull request now.

**Comment by abdulsamad234** [comment]
https://github.com/sugarlabs/www-sugarlabs/pull/198 fixed

**Comment by quozl** [comment]
Yes, I saw.  Please don't post redundant notifications; the pull request is linked already.
