### ISSUE TITLE
http://server.sugarizer.org/ page enhancement

### ISSUE THREAD

**Issue by Saichethan** [sugarlabs/www-sugarlabs#194]
![screenshot from 2018-02-14 22-28-19](https://user-images.githubusercontent.com/34788026/36217036-6a0d746a-11d6-11e8-8d70-da591f2e145e.png)
![screenshot from 2018-02-14 22-28-23](https://user-images.githubusercontent.com/34788026/36217066-82afd68e-11d6-11e8-9643-eab8d88adc5a.png)

**Comment by quozl** [comment]
Not fixable in this repository, as this repository is only for https://www.sugarlabs.org/ ... please raise this in the sugarizer repository or with the Sugarizer team directly.
