### ISSUE TITLE
Consolidating https://github.com/sugarlabs/sugar-docs here

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#20]
I would like to make a PR to import https://github.com/sugarlabs/sugar-docs into this repo, and that repo closed. Will such a PR be accepted?

**Comment by walterbender** [comment]
What exactly is the goal? Would these .md files be found in a developer section of www.sl.o?

**Comment by davelab6** [comment]
The goal is consolidation: put the website sources together into a single repo, so that the pull request reviewing community is consolidated and to show more activity to attract more contributors. 

The integration of the design and intertwining of content can happen without this consolidation, but will be a little easier if they are in a single repo :)

**Comment by davelab6** [comment]
I propose moving the sugar-docs content to sugarlabs.org/develop/

**Comment by Pro-Panda** [comment]
@walterbender,
Should this be closed, since we have moved the documentation to GitHub
