### ISSUE TITLE
A proposal for a chatbot

### ISSUE THREAD

**Issue by anmol27katyani** [sugarlabs/www-sugarlabs#207]
It will help new users to communicate or access data easily
I have tried getting a mock available at [Link]( https://octamois.github.io )

A similar can be deployed and being it free ,serverless and easy to maintain.

**Comment by samswag** [comment]
I like the idea, can you work on it?

**Comment by octamois** [comment]
I can make things fly in 3-4 days.
@samswag, You active on IRC?

**Comment by samswag** [comment]
Sure, you can also mail me

**Comment by quozl** [comment]
Please continue to work in the open.

Also include metrics on conversion rates, so we know if it is worth keeping six months down the track.

**Comment by samswag** [comment]
@octamois want to give more details on it, so I can make it a GCI Task ?

**Comment by pro-panda** [comment]
My opinion is to not add a chatbot.
 - How does it help the audience ? 
   Shouldn't the website itself be descriptive enough to solve any doubts ? Or maybe an FAQ page ?
 - How does it help us ?
 - Do we have enough maintainers for it ?

We already have a lot of mediums for communication (IRC, Mailing List, probably Sugar Social) and data (Wiki, www.sugarlabs.org, GitHub). It'd be better to concentrate on improving them first.
Also see: http://lists.sugarlabs.org/archive/sugar-devel/2018-November/055891.html

**Comment by pro-panda** [comment]
I don't see a consensus in either direction

@samswag @quozl Should we close this ?

**Comment by quozl** [comment]
Agreed, we should not be adding new features now; our situation is too dire for that.

There was a [community meeting](https://wiki.sugarlabs.org/go/Oversight_Board/2018/meeting-log-2018-12-07) which produced a plan and a team to work on A/B testing.  Team is @aperezbios, @samswag, and @perriefidelis.  I'm yet to hear anything from them as a team, but it's early days yet.  

I've asked for a GitHub project and issues to be created.

Getting started with A/B testing can be very simple; an oscillating symlink for index.html should begin to give us data, which we will have to wait for as visitors visit.  This is too urgent an issue to waste time doing anything slowly.

**Comment by samswag** [comment]
Hello @quozl Here is a conversation of the plan http://meeting.sugarlabs.org/sugar-meeting/2018-12-09

**Comment by quozl** [comment]
I'm closing this because we certainly do not have enough volunteers or members to operate the human response side of a web site chat 'bot.
