### ISSUE TITLE
Search bar not proper aligned when screen size reduced

### ISSUE THREAD

**Issue by mann27** [sugarlabs/www-sugarlabs#214]
In safari

![screen shot 2018-05-30 at 2 39 36 pm](https://user-images.githubusercontent.com/33790390/40711321-85e63da4-6418-11e8-9265-fd4e20a078c6.png)

In chrome

![screen shot 2018-05-30 at 2 42 51 pm](https://user-images.githubusercontent.com/33790390/40711394-acd55f4e-6418-11e8-82a8-91d806d2db19.png)

**Comment by nikkuAg** [comment]
Hey,

Is this issue still open?
Can I work on this issue

**Comment by chimosky** [comment]
Hi @nikkuAg, thanks for bringing this to my attention and yes you can work on it.

I'll hold off on closing this issue as you intend to work on it but take a look at #288 for existing discussion on the issue and why I want to close this too.

**Comment by quozl** [comment]
Seems okay now.
