### ISSUE TITLE
Add list of good introductions to libre software culture

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#22]
Since Sugar attracts many people who are new to libre software, and per https://wiki.sugarlabs.org/go/File:Education-needs-free-software.pdf onboarding people to the movement is a primary purpose of Sugar Labs, the website should provide a curated list of good introductions.

I see 3 main areas:

Philosophy / Concepts
- www.gnu.org/philosophy/free-sw.html
- www.gnu.org/gnu/manifesto.en.html
- www.gnu.org/philosophy/selling.html
- http://www.ted.com/talks/luis_von_ahn_massive_scale_online_collaboration
- http://hintjens.com/blog:23 "The Pedantic Code Construction Contract (PC3) is an evolution of the GitHub Fork + Pull Model, and the ZeroMQ C4 process, aimed at providing an optimal collaboration model for commercial software projects. PC3 helps an organization build consistently good software, cheaply, and rapidly."

Processes / Community
- www.catb.org/esr/faqs/smart-questions.html#intro
- www.producingoss.com
- https://help.github.com/articles/good-resources-for-learning-git-and-github/
- https://www.google.com/search?q=daivd%20allen%20getting%20things%20done%20pdf
- http://hintjens.com/blog:117
- http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
- http://www.gweep.ca/~edmonds/usenet/ml-etiquette.html

Programming / Contributing
- https://github.com/OpenTechStrategies/checklist
- https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#python
- https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#javascript
- https://github.com/vinta/awesome-python
- http://joeduffyblog.com/2016/04/10/performance-culture/
- https://education.github.com/pack (Ignacio Rodríguez says "I got that package like a year ago, and its really cool! :D Is not that easy to get it (you need to be a student), it took me few months. But was worth the wait!"
- https://github.com/linuxfoundation/cii-best-practices-badge

Systems Team / Contributing
- https://www.google.com/search?q=practice+of+system+and+network+administration+pdf

What other links are good?

**Comment by davelab6** [comment]
@samdroid-apps any good introduction text you are aware of, stuff like git ?

**Comment by venky18** [comment]
have a look at 
- [Code School's Try Git](https://try.github.io/levels/1/challenges/1) 
- [Git-it](https://github.com/jlord/git-it)
- [GitHubGuides](https://www.youtube.com/user/GitHubGuides) - GitHub Training & Guides on YouTube.
- https://github.com/phillipadsmith/awesome-github

**Comment by davelab6** [comment]
http://vlsicad.ucsd.edu/Research/Advice/network.html is not directly relevant to libre culture but is important for young people to learn how to use the net effectively

**Comment by quozl** [comment]
Stale, closing.
