### ISSUE TITLE
Problem in dropdown menus of navbar

### ISSUE THREAD

**Issue by aastha980** [sugarlabs/www-sugarlabs#225]
When we click on some navbar links and then hover on other links, undesired output is obtained. Other dropdowns go either behind or in front of opened dropdown.

![aa](https://user-images.githubusercontent.com/29335511/44155880-0eb264a6-a0cc-11e8-8945-b2073ad297c6.JPG)

**Comment by quozl** [comment]
Yes, I see that too.  As a workaround, you should either click or hover, not both.

**Comment by steve7158** [comment]
can this be a solution if we make the hover not to work whenever the click is activated?

**Comment by amaaniqbal** [comment]
Issue already fixed! I am closing it.
