### ISSUE TITLE
No mention of OLPC

### ISSUE THREAD

**Issue by sdalybe** [sugarlabs/www-sugarlabs#23]
It's important to mention SL's roots in OLPC, for SEO.

Text in the What is Sugar Labs? section should be:

"a volunteer-driven, non-profit organization, had its origins in the One Laptop Per Child project and is now a member project of the Software Freedom Conservancy."

**Comment by davelab6** [comment]
I suggest adding the acronym after the name, eg from

> the One Laptop Per Child project 

to

> the One Laptop Per Child (OLPC) project

**Comment by sdalybe** [comment]
Heartily agree, even better for SEO
I disdain acronyms in general, but this will be helpful.
