### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#232]
At last commit, GitHub reported three dependencies with security issues yet to be resolved, details at https://github.com/sugarlabs/www-sugarlabs/network/dependencies

![screen shot 2018-10-14 at 1 18 22 pm](https://user-images.githubusercontent.com/2936481/46911876-cd952780-cfb3-11e8-8326-9b894e6ceed2.png)

I've reviewed each of the CVEs, and we have nothing to worry about, as the site does not store information for users, does not have registrations, and does not permit file uploads.

But still, it's unprofessional to leave the site dependencies languishing like this, and they should be updated by someone who knows how to do it.  That's not me, so I'm raising this as an issue for someone else to look at.

**Comment by samswag** [comment]
I am working on it. Thanks for the report @quozl

**Comment by samswag** [comment]
I just fixed the security issues
