### ISSUE TITLE
Proposal for a Privacy Policy

### ISSUE THREAD

**Issue by nathan-jacob** [sugarlabs/www-sugarlabs#237]
I want to add a privacy policy to the website, given that the site currently does not have one.

**Comment by nathan-jacob** [comment]
added better HTML headings, added links for websites and changed the font to Roboto.

**Comment by nathan-jacob** [comment]
here's a mock up: [here](https://codepen.io/nathanjacob/pen/ReYgbr)

**Comment by quozl** [comment]
Really this is a matter for the governing body.
