### ISSUE TITLE
Proposal For a Feedback page

### ISSUE THREAD

**Issue by nathan-jacob** [sugarlabs/www-sugarlabs#238]
Well, I thought the page could use a feedback section, because a lot of kids don't know how to use GitHub issues/comment, and it could be beneficial to get feedback from them. Mockup [here](https://codepen.io/nathanjacob/pen/bmxRWa)

**Comment by quozl** [comment]
How will the feedback be read and answered?  Let's not add something we can't sustain or handle.

**Comment by nathan-jacob** [comment]
I was thinking it would send an email to a mailing list, which we could then just reply through email to address whatever issue

**Comment by quozl** [comment]
Thanks.  We'd also have to moderate the submissions.  Plenty of 'bots out there are filling in feedback and comment forms with advertising, political, or hate-speech.  The "check for human" or captcha services are not fully reliable.

We did have a Discourse forum, and we do still have a MediaWiki instance, and the mailing lists.

Hopefully others will contribute to this discussion.

**Comment by nathan-jacob** [comment]
@quozl what about google forms? That way there is no server involvement, and on top of that everyone can see the data?
