### ISSUE TITLE
Intro doesn't mention nonprofit/volunteer

### ISSUE THREAD

**Issue by sdalybe** [sugarlabs/www-sugarlabs#25]
We have always been assumed to be a for-profit startup.

Intro text should be:

"At Sugar Labs, we make a collection of tools that learners use to explore, discover, create, and reflect. We are nonprofit and staffed by volunteers. We distribute these tools freely and encourage our users to appropriate them, taking ownership and responsibility for their learning."

**Comment by davelab6** [comment]
With the new translations manager being paid monthly, while SLOBs are all unpaid, I suggest replacing

> We are nonprofit and staffed by volunteers.

with

> We are nonprofit and led by volunteers.

**Comment by sdalybe** [comment]
hee hee that makes three dozen leaders and 1 worker
it's not just the SLOBs who are unpaid, it's everyone else... until now
I guess "led by volunteers" is OK but later on we will bump into why some members will get contracts and others not.
Fully support cjl by the way.

**Comment by sdalybe** [comment]
discovering that posting a comment means closing it... except it's not

**Comment by davelab6** [comment]
Admins have 2 buttons, close and command, and comment :)

**Comment by davelab6** [comment]
And, I don't mean to imply any lack of support for CJL! I'm very happy when any free software project pays for labour.
