### ISSUE TITLE
Proposal to modify social icons on footer

### ISSUE THREAD

**Issue by BolajiAyodeji** [sugarlabs/www-sugarlabs#252]
Footer icons on footer can be modified to use relative and equal icon types.

**Comment by quozl** [comment]
We don't need or want an issue for something that you are willing to fix in a pull request.  An issue is for something you aren't willing to fix.  So I had presumed @BolajiAyodeji didn't want to fix it.  @BolajiAyodeji, do you want to fix this?

**Comment by BolajiAyodeji** [comment]
@quozl Yes, I would fix that

**Comment by quozl** [comment]
Thanks, let's see your pull request then.
