### ISSUE TITLE
No Year in Sugar Labs Copyright

### ISSUE THREAD

**Issue by nathan-jacob** [sugarlabs/www-sugarlabs#266]
In the footer of sugar labs, there is no year stated when we claim the Creative Commons Attribution-ShareAlike 4.0 International License(CC-BY-SA).

**Comment by AjjuSingh** [comment]
I can fix this issue.

**Comment by akshgpt7** [comment]
@nathan-jacob Is this issue still up for grabs?

**Comment by quozl** [comment]
Sorry, but it was quicker for me to fix it than answer.
