### ISSUE TITLE
Activities Downloaded #

### ISSUE THREAD

**Issue by nathan-jacob** [sugarlabs/www-sugarlabs#267]
![image](https://user-images.githubusercontent.com/37455968/48972323-59579600-efed-11e8-9a28-389c5c924234.png)
Here the number of sugar users has a plus, but the number of activities downloaded does not. I know for a fact that this number is not exact, so why not put a plus on it too?

**Comment by samswag** [comment]
Did you send any PR to address this issue, because I can't find any?
