### ISSUE TITLE
Improve the design of fixed social media hyperlinks on main page

### ISSUE THREAD

**Issue by akshat0047** [sugarlabs/www-sugarlabs#293]
- Fix the border radius of inner corners
- Add box shadow

![Screenshot from 2019-03-28 03-20-38](https://user-images.githubusercontent.com/32462195/55114697-a917ac80-5108-11e9-9ce3-d47234bd16d7.png)

**Comment by quozl** [comment]
@akshat0047, in future if you make a pull request for an issue, please add the words "fixes" followed by the issue number, so it will be closed automatically.  I agree with @Aniket21mathur that there's no need to create an issue if you plan to make a fix.  It saves on notification noise for everybody.
