### ISSUE TITLE
Social media buttons 

### ISSUE THREAD

**Issue by IfeanyiEkperi** [sugarlabs/www-sugarlabs#306]
In the footer section, the Social media buttons are rioting with the background in my opinion.

As an advocate of 'Design with Inclusion' I think some icons may be difficult to identify in the dark background, hence, I suggest the icons be changed to white color to make it as visible as possible.

**Comment by quozl** [comment]
I don't think this is important.  The site is dead, as it has too little recent content.

**Comment by IfeanyiEkperi** [comment]
Hmmm, isn't that supposed to be a disturbing news.

We can create contents and keep it alive. It's also nice GCI is around the corner, I think tasks on contents should be geared towards keeping Our website contents as fresh and lively as possible.

**Comment by quozl** [comment]
No, I'm not trying to be disturbing.  It's just the ways things are; the people who are doing anything with Sugar Labs tend to be either;

* coding and releasing Sugarizer, Music Blocks, Sugar or activities,
* maintaining the existing web services,
* managing the organisation (the oversight board), or;
* tweaking icons, spelling or formatting on web sites and the Wiki.

> We can create contents and keep it alive.

We aren't able to keep the existing content alive, so I don't think we'd be able to keep new content alive.

> It's also nice GCI is around the corner, I think tasks on contents should be geared towards keeping Our website contents as fresh and lively as possible.

This is not sustainable.  It is overreach.  We need regular content all through the year, not bursts of content from students.  The content needs to come from people who are active in using, testing, or developing Sugarizer, Music Blocks, and Sugar.  Which of this do you do?

**Comment by quozl** [comment]
I'm a designer of code and complex systems.  By _designer_, I think you mean you create imagery and web content using web publishing applications rather than write it by hand?  I'd call that a _web designer_.

So, let's check for suitability for the task.  Do you use or test Sugarizer, Music Blocks, or Sugar?

**Comment by IfeanyiEkperi** [comment]
Yes you're right, I'm a web designer and Graphic Artist.
 
I do test Sugarizer

**Comment by quozl** [comment]
Excellent, I"ll expect content about Sugarizer then.  Thanks for the offer.

**Comment by IfeanyiEkperi** [comment]
Thank you so much, it's been great having this thread with you. I'll work on it and start contributing as advised.
