### ISSUE TITLE
social media icons create a weird line on hover

### ISSUE THREAD

**Issue by pidddgy** [sugarlabs/www-sugarlabs#308]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/30125762/69692238-634c2300-109f-11ea-9377-2e5611a3c047.png">

<img width="982" alt="image" src="https://user-images.githubusercontent.com/30125762/69692254-6d6e2180-109f-11ea-9eea-ae24c084373c.png">

**Comment by quozl** [comment]
Not important to fix.  It is only an appearance problem.  More important is to verify and update the content on the web site, and remove content that is not maintained.  See also https://github.com/sugarlabs/www-sugarlabs/issues/305 and other closed issues for related discussion.
