### ISSUE TITLE
suggession: Replace some words that can be replaced with material icons

### ISSUE THREAD

**Issue by thushan-sen** [sugarlabs/www-sugarlabs#314]

**Comment by Thusal06** [comment]
I would like to work on this issue.

**Comment by Thusal06** [comment]
Can you explain this further?

**Comment by thushan-sen** [comment]
the website would be neat and organized and anyone can  easily understand the various elements in the page by using material icons rather than using words. So i think using material icons will improve the quality of the webpage. 

> Can you explain this further?

the website would be neat and organized and anyone can  easily understand the various elements in the page by using material icons rather than using words. So i think using material icons will improve the quality of the webpage.

**Comment by thushan-sen** [comment]
> Can you explain this further?

the website would be neat and organized and anyone can  easily understand the various elements in the page by using material icons rather than using words. So i think using material icons will improve the quality of the webpage.

**Comment by thushan-sen** [comment]
> I would like to work on this issue.

ya pls

**Comment by quozl** [comment]
I'm not interested.  The issue is not sufficiently described and no example is given.

**Comment by quozl** [comment]
This in conjunction with other recent issues and pull requests looks like a denial of service attack on our organisation.  Could you please explain why you have become interested in our web site?  Has someone asked you to be involved?  Is there a bounty?  Are we on some list somewhere?  I'd like to get us removed from any such list.

**Comment by quozl** [comment]
That's no answer.  :grin:
