### ISSUE TITLE
Have a link labeled 'Home' on every page on the site, except for the home page.

### ISSUE THREAD

**Issue by SDR0512** [sugarlabs/www-sugarlabs#315]
Many sites place the organization's logo on the top of every page and link it to the homepage. While many users expect logos are clickable, around 25% will not realize that links to the homepage. Therefore, include a link labeled 'Home' near the top of the page to help those users.

**Comment by quozl** [comment]
Thanks.  I don't believe this is necessary.  In my experience less than 5% (rather than 25%) do not realize that the logo links to a home page.  Also, we very rarely need a way to navigate to the home page, as the site is small.
