### ISSUE TITLE
Create touch icon 

### ISSUE THREAD

**Issue by SDR0512** [sugarlabs/www-sugarlabs#319]
Use a memorable logo as the touch icon so your website will make a good impression as a bookmark on mobile devices.

**Comment by quozl** [comment]
Thanks, but I'm not sure you are serious.  The wording of your issues seems scripted, and I've seen it before.  e.g. ["Use a memorable logo as the touch icon so your"](https://www.google.com/search?q=%22Use+a+memorable+logo+as+the+touch+icon+so+your%22).  Your other contributions to other projects also seem remarkably patterned.  Perhaps you are a robot.  Are you a real person?  Have you used Sugar?
