### ISSUE TITLE
Contribute to website option on footer

### ISSUE THREAD

**Issue by himanshujaidka** [sugarlabs/www-sugarlabs#323]
Contribute to website link will not change its color when we hover on it
![Screenshot (714)](https://user-images.githubusercontent.com/58654018/86538731-651f7400-bf15-11ea-9020-5b611f8592aa.png)

**Comment by quozl** [comment]
This is insignificant.

**Comment by himanshujaidka** [comment]
All links in website changes its color to pink but only one link (contribute to website) will not change its color while hovering on it, it is not looking goods

**Comment by quozl** [comment]
Sure, it's not the best, but we have _way more important_ problems with the web site, such as actual content relating to Sugarizer, Sugar and Music Blocks.  Please don't distract us from important problems with stuff like this?

**Comment by himanshujaidka** [comment]
Yeah, sure I would like to remove that link :)

**Comment by himanshujaidka** [comment]
Pls, assign this to me I will remove that link

**Comment by quozl** [comment]
This in conjunction with other recent issues and pull requests looks like a denial of service attack on our organisation.  Could you please explain why you have become interested in our web site?  Has someone asked you to be involved?  Is there a bounty?  Are we on some list somewhere?  I'd like to get us removed from any such list.

**Comment by himanshujaidka** [comment]
No! nothing like that :) Actually I want to take part in GSoC 2021 so for that I am preparing and I am very passionate about it. Would you mind if you will guide me and I also want to improve your website because I love to design websites :)

**Comment by quozl** [comment]
Thanks!  Looking at your profile, we could really do with help on Sugar, Sugarizer and Music Blocks.
