### ISSUE TITLE
Moving the website to GitHub Pages (Discussion)

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/www-sugarlabs#332]
I put forward a proposal to move the website to GitHub Pages, after a series of problems on _Machine/freedom_. 
* The docker container www-rebuilder doesnt work anymore.
* The latest commits, eg: The Flatpak commit by @tchx84 is not deployed yet.
* _Machine/freedom_ would probably retire soon.

GitHub Pages has a fast built-in Jekyll Processor, which would automatically build this website and deploy it to https://sugarlabs.github.io/www-sugarlabs. By setting a CNAME on our nameservers, we should be then be able to point `www.sugarlabs.org -> https://sugarlabs.github.io/www-sugarlabs`. This would bring forth faster builds, Pull Request Previews, and much more.

**Comment by srevinsaju** [comment]
cc @sugarlabs/sugar-labs-inc

**Comment by samswag** [comment]
Github pages do have limitations, maybe netlify sounds like a good plan, we can apply for an open source plan.

**Comment by srevinsaju** [comment]
May I know what are the limitations of GitHub Pages?

**Comment by samswag** [comment]
Here you go [Netlify Vs Github](https://www.netlify.com/github-pages-vs-netlify/#:~:text=If%20you%20are%20hosting%20a,easy%20to%20deploy%20your%20site.&text=Netlify%20works%20out%20of%20the,your%20Git%20repo%20to%20Netlify.)

**Comment by srevinsaju** [comment]
> Here you go [Netlify Vs Github](https://www.netlify.com/github-pages-vs-netlify/#:~:text=If%20you%20are%20hosting%20a,easy%20to%20deploy%20your%20site.&text=Netlify%20works%20out%20of%20the,your%20Git%20repo%20to%20Netlify.)

Interesting, its a feature list provided by Netlify itself. 

How would Netlify benefit Sugar Labs over GitHub Pages (considering only Sugar Labs, and the features used by the current website)
* Isn't Netlify another level of complexity?
* Wouldn't that require additional credentials, which you would need to maintain?
* What would happen if the owner of the Netlify repository stops contributing?
* Wouldn't it be better if we have all the information at one place?

I have been using Netlify, and GitHub Pages. I feel Netlify has higher performance over all cases, but in the case of Sugar Labs, in my opinion, it looks like an overkill. What do you think?

**Comment by samswag** [comment]
I totally agree with you, I also believe in future-proofing. The website or at this currently will be changing soon, so maybe in future, some decisions can make us want to port. 

Since netlify has what Github pages offer, we can consider that too.

**Comment by quozl** [comment]
My preference is to scale down the number of different tools to an absolute minimum in line with the number of active developers we have.

We are also an open source project, and as part of our mission should think carefully before using proprietary services, independent of service cost.  GitHub is proprietary, and we aren't unduly affected by the proprietary nature of GitHub.

Also, @sugarlabs/sugar-labs-inc only contains two of the current board, so I've not been using it.

**Comment by samswag** [comment]
Agreed, as per @sugarlabs/sugar-labs-inc I see not in there, maybe @aperezbios can address that.

**Comment by quozl** [comment]
Per https://github.com/orgs/sugarlabs/people there are plenty of people who can address it.  But the board members are the ones obliged to do so.

**Comment by srevinsaju** [comment]
> My preference is to scale down the number of different tools to an absolute minimum in line with the number of active developers we have.

Agreed. We have few sysadmins to actively devote enough time to maintain our own infrastructure. Wherever possible, I feel using GitHub Pages for serverless static page deployment is ok. GitHub Pages does not use any cookies, as compared to Netlify iirc. So privacy-wise, I suppose its okay to not use any other extra addition to the current website. In future, for example, if we rewrite the website in `hugo`, ([gohugo.io](https://gohugo.io)), we can think of another service.

> 
> We are also an open source project, and as part of our mission should think carefully before using proprietary services, independent of service cost. GitHub is proprietary, and we aren't unduly affected by the proprietary nature of GitHub.

Agreed.

> 
> Also, @sugarlabs/sugar-labs-inc only contains two of the current board, so I've not been using it.

Ok.

**Comment by rahul-bothra** [comment]
My comments after https://github.com/sugarlabs/www-sugarlabs/issues/333#issuecomment-841637207,

Developers should have to spend minimal time maintaining the website and wiki, and more on building Sugar, Sugarizer, and Music Blocks. GitHub pages should do a good job at reducing maintenance. While GitHub is a proprietary service, this dependency was partly already taken as GitHub is used to host the source code.

View comments with the light that I'm not an active member anymore, and I won't be the developer actually spending time to fix and maintain this

**Comment by chimosky** [comment]
I think we need to address this as it's lingered long enough, I do agree with moving to Github pages as there will be very little to do about maintenance.

**Comment by chimosky** [comment]
Closing this as the website has been moved to GH pages.

**Comment by aperezbios** [comment]
The migration is not successful. The website is still 404 as of just now. This is not complete.

**Comment by chimosky** [comment]
It works fine for me, can someone else confirm?

**Comment by rahul-bothra** [comment]
Where is the website building from?
https://sugarlabs.org/profiles/ is not updated with my patch 2a40dfb

**Comment by chimosky** [comment]
> Where is the website building from?
> https://sugarlabs.org/profiles/ is not updated with my patch [2a40dfb](https://github.com/sugarlabs/www-sugarlabs/commit/2a40dfbbd3c3f272ef1c6f6bc74e0c519aca9c1a)

It's building from this repo, I'll check why it's not showing your change later as it was showing it before now.

@srevinsaju seems like the CNAME doesn't currently point to sugarlabs.github.io but dig shows that it does, GH says it doesn't.

**Comment by srevinsaju** [comment]
```bash
% dig www.sugarlabs.org

; <<>> DiG 9.16.16 <<>> www.sugarlabs.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20310
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.sugarlabs.org.             IN      A

;; ANSWER SECTION:
www.sugarlabs.org.      2711    IN      CNAME   sugarlabs.github.io.
sugarlabs.github.io.    2711    IN      A       185.199.110.153
sugarlabs.github.io.    2711    IN      A       185.199.109.153
sugarlabs.github.io.    2711    IN      A       185.199.111.153
sugarlabs.github.io.    2711    IN      A       185.199.108.153
```

I am getting annoyed with local DNS caches, and I have no clue how to purge them. So, I am not sure if this is my PC alone, it would be nice i someone else could test it.

**Comment by srevinsaju** [comment]
> It's building from this repo, I'll check why it's not showing your change later as it was showing it before now.

It might come from the subsequent commits, as it is just set up today.

**Comment by srevinsaju** [comment]
oh, nvm. Looks like sugarlabs.org now includes https://github.com/sugarlabs/www-sugarlabs/commit/2a40dfbbd3c3f272ef1c6f6bc74e0c519aca9c1a commit

**Comment by aperezbios** [comment]
It's working from my location now.

**Comment by aperezbios** [comment]
Final step is to update the documentation on the wiki, so we have the new process for updating the website actually documented somewhere :)

**Comment by chimosky** [comment]
> Final step is to update the documentation on the wiki, so we have the new process for updating the website actually documented somewhere :)

I think it'll be just to state that all changes are built automatically as we've moved to GH Pages.

**Comment by srevinsaju** [comment]
> Final step is to update the documentation on the wiki, so we have the new process for updating the website actually documented somewhere :)

I have updated the wiki. Removed the obsolete instructions, and added the steps to update the website now. 

Basically, to update the website: all we need to do is, to push a commit to `master`, which will trigger the pipelines to refresh the website.

**Comment by aperezbios** [comment]
> Basically, to update the website: all we need to do is, to push a commit to `master`, which will trigger the pipelines to refresh the website.

Great. How those pipelines/automation bits actually work is also important to document, so someone who is going in to troubleshoot _why_ that automation might fail is going in fully-armed with the knowledge they need to troubleshoot it without prior knowledge. Are there any explanations or links to how the automation works?

**Comment by srevinsaju** [comment]
Agreed, you are right. I have added https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll this link to the wiki page to help debug future builds. This link has the entire information on how to set up the continuous integration system, setting up a custom domain, and troubleshooting jekyll builder bugs. 

In short, When a user with push access, pushes to the `master` branch, the following things happen under the hood:
* A GitHub builder workflow would be automatically triggered (this workflow is enabled in the repository setting by a repository maintainer, in this case, its @chimosky. It can be disabled from the same `Settings > GitHub Pages` section )
* Jekyll builder is run, and the static files are hosted on GitHub's servers (4 of them, for load balancing), and the `CNAME` file placed at the root, helps GitHub to tell which custom domain to host it from.
* The static files are then displayed by a "Headless CMS", a jamstack service offered for open source as well as private repos, under GitHub.

**Comment by quozl** [comment]
Consider also how many people have push access now.  It is a large
list.

**Comment by srevinsaju** [comment]
Perhaps, we should mark `master` as a protected branch to restrict the number of users with the ability to deploy the website to the CMS. :thinking:

**Comment by chimosky** [comment]
> Consider also how many people have push access now. It is a large list.

For the website, I've restricted some of the outside collaborators to read only. Also restricted some member access to the needed repos.
