### ISSUE TITLE
Contributor Page Improvement

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/www-sugarlabs#335]
I think the [contributor page](https://sugarlabs.org/profiles) on the website needs improvement as it's currently not pleasant to look at as it has quite tiny text, varying font size and there's no arrangement of the content.

**Comment by Anubhavdxt** [comment]
Hey @chimosky 
I would like to work on this issue. I'm a newbie in the open-source world. 
If no one else is working on it, can you please guide me?

**Comment by chimosky** [comment]
Hey @Anubhavdxt, thanks for wanting to work on this.

The current contributors page - linked in the opening comment above - can look better than it currently does, you're to come up with a design of choice and change how the page looks, we can discuss the options you can up with an agree on which to use.

This [one](https://www.kernel.org/doc/html/latest/driver-api/media/drivers/contributors.html) from the linux kernel is quite simple and good looking., so you're looking at implementing something similar.

You might also want to at a look at the [contributing section](https://github.com/sugarlabs/www-sugarlabs#code-and-contribution) of the website as it shows how to test your changes.

Let me know if you have anymore questions.

**Comment by Anubhavdxt** [comment]
Hey @chimosky 
I've gone through the page you've mentioned above, it looks very clean and nice, I would like to implement something similar.
Are there any directions or advice for me to get started on this?
Help me out on getting started with the issue.

**Comment by chimosky** [comment]
> Hey @chimosky
> I've gone through the page you've mentioned above, it looks very clean and nice, I would like to implement something similar.
> Are there any directions or advice for me to get started on this?
> Help me out on getting started with the issue.

You'd need to setup a dev environment so that you can test your changes and that's detailed in the contributing guide I linked above, the task requires knowledge of html and css, I don't know what files to make the change to so that's why I opened the issue and you'll have to figure that out.

**Comment by Anubhavdxt** [comment]
Hey @chimosky 
Could you please assign me the issue so that I can start working on it?

**Comment by chimosky** [comment]
> Hey @chimosky
> Could you please assign me the issue so that I can start working on it?

We usually don't assign issues as that can sometimes prevent others from working on an issue when anyone can work on it and we accept the solution that seems good for us, I don't think anyone is working on this at the moment though so you're free to open a PR with your changes.

**Comment by nikkuAg** [comment]
Hello @chimosky,

If the issue has not been assigned to anybody yet, can I work on it?

**Comment by chimosky** [comment]
Hi @nikkuAg, yes the issue isn't assigned to anyone and you can work on it.

**Comment by kartiktom** [comment]
Hi  I want to contribute to this feature can you help me set up the project I am currently using VS code for development. I followed the instruction but was not able to set it up.

**Comment by nikkuAg** [comment]
> Hi @nikkuAg, yes the issue isn't assigned to anyone and you can work on it.

Hello @**chimosky**,

I have started the work on the design. 
I want to confirm if I just have to add CSS or I can add some feature like search option for better user experience

**Comment by nikkuAg** [comment]
> Hi @nikkuAg, yes the issue isn't assigned to anyone and you can work on it.

Hi **@chimosky**,

I have tried to improve the design of the contributor's page. So should I create a pull request or is there any other way to review the changes

**Comment by quozl** [comment]
In deleted comments someone asked if a search feature was needed.  I don't think so.  I can't see why a search would be needed.  The page is a list of contributors, as a thank you to them for their work on Sugar.

(It is also out of date, and doesn't list contributors for other Sugar Labs software, such as Music Blocks or Sugarizer.  It isn't clear how a contributor can be added to the list.)

**Comment by chimosky** [comment]
> Hi @chimosky I want to contribute to this feature can you help me set up the project I am currently using VS code for development. I followed the instruction but was not able to set it up.

Hi @kartiktom, do you mean the instructions [here](https://github.com/sugarlabs/www-sugarlabs#code-and-contribution) and can you explain what you mean by not being able to set it up, what did you try and what errors did you encounter?

**Comment by chimosky** [comment]
> In deleted comments someone asked if a search feature was needed. I don't think so. I can't see why a search would be needed. The page is a list of contributors, as a thank you to them for their work on Sugar.
> 
> (It is also out of date, and doesn't list contributors for other Sugar Labs software, such as Music Blocks or Sugarizer. It isn't clear how a contributor can be added to the list.)

I agree with you about the search feature, I don't think it's necessary too and yes it's outdated and omits a lot of contributors as no one really want to take the time to update it as the developers who have their names there mostly added it after it was first curated and I don't think anyone wants to update it either as I haven't seen anyone indicate interest in doing so.

**Comment by kartiktom** [comment]
> > Hi @chimosky I want to contribute to this feature can you help me set up the project I am currently using VS code for development. I followed the instruction but was not able to set it up.
> 
> Hi @kartiktom, do you mean the instructions [here](https://github.com/sugarlabs/www-sugarlabs#code-and-contribution) and can you explain what you mean by not being able to set it up, what did you try and what errors did you encounter?

@chimosky I followed instructions but the bundle install command is not working in VS Code.

**Comment by chimosky** [comment]
> @chimosky I followed instructions but the bundle install command is not working in VS Code.

You probably don't have ruby installed but can you share the error you get when you run `bundle install`?

**Comment by kartiktom** [comment]
> > @chimosky I followed instructions but the bundle install command is not working in VS Code.
> 
> You probably don't have ruby installed but can you share the error you get when you run `bundle install`?

The term 'bundle' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
can you please guide me how to install ruby

**Comment by chimosky** [comment]
> The term 'bundle' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. can you please guide me how to install ruby

I don't know what OS you use but you can easily search for how to install it in your OS.

**Comment by kartiktom** [comment]
> > The term 'bundle' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. can you please guide me how to install ruby
> 
> I don't know what OS you use but you can easily search for how to install it in your OS.

I installed Ruby still the same error (I am using windows).

**Comment by chimosky** [comment]
> I installed Ruby still the same error (I am using windows).

I don't use windows and can't really help you there so you'll have to search and figure out how to fix it, you can start by searching the error you got and move from there.

**Comment by kartiktom** [comment]
> > I installed Ruby still the same error (I am using windows).
> 
> I don't use windows and can't really help you there so you'll have to search and figure out how to fix it, you can start by searching the error you got and move from there.

Can I work on this issue or someone else is already working ?

**Comment by chimosky** [comment]
> Can I work on this issue or someone else is already working ?

Yes you can work on the issue and I don't think anyone is working on it as no one has indicated that they are.

**Comment by quozl** [comment]
It is fine for more than one person to work on an issue, and we resolve that during pull requests.

**Comment by kartiktom** [comment]
@quozl you were saying that the data is too old so It would be a waste of time to work on this data.
So can you please help me with updated data?

**Comment by nikkuAg** [comment]
> In deleted comments someone asked if a search feature was needed. I don't think so. I can't see why a search would be needed. The page is a list of contributors, as a thank you to them for their work on Sugar.
> 
> (It is also out of date, and doesn't list contributors for other Sugar Labs software, such as Music Blocks or Sugarizer. It isn't clear how a contributor can be added to the list.)

Hi @quozl,

To add new contributors data, we just need to update the exisiting file having the list of all the contributors with their respective data.

**Comment by nikkuAg** [comment]
> > Can I work on this issue or someone else is already working ?
> 
> Yes you can work on the issue and I don't think anyone is working on it as no one has indicated that they are.

Hi @chimosky,

I am also working on this issue and have create one PR.
I will be updating the changes mentioned in the PR

**Comment by quozl** [comment]
@kartiktom wrote:
> @quozl you were saying that the data is too old so It would be a waste of time to work on this data.

It is certainly odd.  Almost as if you care more about making a change to how it looks than ensuring Sugar Labs communicates correctly and truthfully with readers.  There are colloquial phrases in various cultures, and sorry for any cross-cultural offense, but in my culture it could be "putting a dress on a pig doesn't change the fact that it is still a pig".

> So can you please help me with updated data?

Of course not.  If I had the data I'd make a pull request.  To make some data, run `git log` on each repository, measuring the number of lines of change (e.g. diffstat) and recording the author of each commit, and then sort by either date or number of changes.

@nikkuAg wrote:
> To add new contributors data, we just need to update the exisiting file having the list of all the contributors with their respective data.

Yes, of course.

**Comment by lakshya-dhariwal** [comment]
Is anyone working on this issue . 
If yes I think it might be better if you post your mockups and we all can give our opinions .
Also if we have the mockups multiple people can work on different parts of the page.

**Comment by quozl** [comment]
On the other hand, don't overdo it.  I'd prefer to see the page using the styles that Bootstrap already provides, so that the site is consistent across different pages, and so that we can minimise time spent on style and maximise time spent on updating content.

**Comment by quozl** [comment]
Don't worry about that.  Just work on it if you can.  If there is more than one pull request, the first one that is merged obliges the second one to rebase.

**Comment by lakshya-dhariwal** [comment]
Hey @quozl  
Where can i ask doubts ? The IRC seems dead

**Comment by srevinsaju** [comment]
> Where can i ask doubts ? The IRC seems dead

The [sugar-devel mailing list](https://lists.sugarlabs.org/listinfo/sugar-devel) is the best place to post your queries.

**Comment by quozl** [comment]
Thanks, great questions.

Yes, the IRC is unused.  I'm happy to take random questions by either GitHub issue, pull request, or sugar-devel@ mailing list.  Where a discussion moves to the mailing list, remember to summarise or link from GitHub.

Yes, the data for contributors is maintained in profiles.md, and is to be converted to HTML by [Jekyll](https://en.wikipedia.org/wiki/Jekyll_(software)) according to README.md.  You're proposing we stop using Jekyll because it is easier for you?  Pardon me while I giggle quietly behind my hand.  :grin:  Learn how to use Jekyll?
