### ISSUE TITLE
Change hyperlinks for Get Sugar and add a hypertext for Trisquel Sugar

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/www-sugarlabs#342]
The current way to get `SOAS` on the website leads to the `SOAS` [installation page](https://wiki.sugarlabs.org/go/Sugar_on_a_Stick/Installation) on the wiki but I think it should lead [here](https://wiki.sugarlabs.org/go/Sugar_on_a_Stick) instead as it provides specifically useful and updated information.

Also add a hyper text for Trisquel sugar which should lead [here](https://wiki.sugarlabs.org/go/Trisquel_On_A_Sugar_Toast).

@S-kus this might interest you.

**Comment by S-kus** [comment]
@chimosky Thank You for this issue.
Can you confirm where do you exactly want the hypertext for Trisquel Sugar?

**Comment by chimosky** [comment]
> @chimosky Thank You for this issue. Can you confirm where do you exactly want the hypertext for Trisquel Sugar?

It should be part of the `Get Sugar` drop down on the website.

**Comment by kartiktom** [comment]
#346 Hi @chimosky I have created the pull request for this issue. Kindly look into this
