### ISSUE TITLE
Upgrade jquery

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#349]
* [x] jquery 2.2.4 is in `js/jquery.js`, but latest is 3.6.0,
* [x] _layouts/base.html uses a CDN instead of local copy, we should use our local copy.

**Comment by Priyanshi-Raj** [comment]
Hi, can I work on this issue?

**Comment by chimosky** [comment]
> Hi, can I work on this issue?

Hey @Priyanshi-Raj yes you can work on the issue, you should also take a look at our [contributing guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) and open a PR when you have a fix.

**Comment by nikkuAg** [comment]
Hi, can I work on this issue if no one has been assigned.

**Comment by chimosky** [comment]
> Hi, can I work on this issue if no one has been assigned.

Hey @nikkuAg yes you can work on the issue, see my response above too.

**Comment by nikkuAg** [comment]
Hey @chimosky,

Can you please review the PR which is regarding updating jquery to the newest version.
PR: #369

**Comment by quozl** [comment]
You forgot a "fixes #349".  :grin:
