### ISSUE TITLE
Update jsquery.nicescroll

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#351]
* [ ] jquery.nicescroll 3.6.8 is in `js/jquery-nicescroll.js`, but latest is 3.7.6,
* [ ] jquery.nicescroll 3.6.8 is taken from CDN by `_includes/footer.html` instead of from `js/`

**Comment by S-kus** [comment]
Here `nicescroll` is used just for the scrolling of the second header in `#sidebar`. We can do this without any extra files, i.e. just by adding some CSS styles in the default scrollbar.
I have tried and it's working similarly to the earlier one. As shown:
### Earlier:
![before](https://user-images.githubusercontent.com/86892991/150528029-026d5c2b-453f-4203-a605-e4cb3160b214.png)

### Now:
![after](https://user-images.githubusercontent.com/86892991/150528066-d01b55d7-64b2-4e6c-9bea-325ccbf09b02.png)

For this, I just added css in `#sidebar` from `airspace.css ` and removed the old `js/jquery-nicescroll.js`.
@quozl what are your opinions about this?

**Comment by quozl** [comment]
I'll defer my opinion until I see the change.  If we can avoid having to maintain a dependency, that is better.

**Comment by S-kus** [comment]
> I'll defer my opinion until I see the change.

@quozl Should I raise a pr for this with commit messages?

**Comment by chimosky** [comment]
> @quozl Should I raise a pr for this with commit messages so that you can see changes or should I send screenshots of styles in this thread?

A PR would be better.

**Comment by S-kus** [comment]
Thanks, @chimosky.
I created the pr for this, Please review it.
