### ISSUE TITLE
Modernizr unused

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#352]
`js/modernizr.min.js` is present but no code references Modernizr; if it is not used it should be removed.

**Comment by S-kus** [comment]
@quozl Should I just remove it and create a pr? For this, I need to remove its link from the script tag and other required places.

**Comment by quozl** [comment]
Sorry, I don't know how to do it.  Let me know if you do.

**Comment by S-kus** [comment]
@quozl Please review it.
