### ISSUE TITLE
Update ionicons

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#353]
ionicons.min.css is version 2.0.0, but latest release of ionicons is version 6.0.0

**Comment by shubhayu09** [comment]
Hey @quozl,
I would like to take up this issue. Can you pls elaborate on this issue in detail and tell me where to start as I'm new to this community.

**Comment by quozl** [comment]
Thanks.  I don't mind who fixes this issue.  The reason I created the issue was that I saw the difference in version numbers and I didn't have the knowledge and experience to know what to do about it, nor did I have the time to acquire that.  So please be specific on how you want me to elaborate on the issue given that I don't have knowledge, experience, or the time to acquire them.  If I did, I would have fixed it myself, as it would be faster than explaining it to someone who doesn't have the knowledge or experience.  If you have the knowledge and experience, please proceed.  As should anyone else.  However, if you don't have the knowledge and experience, but you have the time to acquire these, then do so.  Don't expect me to be able to verify in detail.  All I did was notice the difference.  In general, using old versions of software without updating them is dangerous because it can lead to software security vulnerabilities.

**Comment by shubhayu09** [comment]
Ok, I got it.
Will try my best to fix this.

**Comment by chimosky** [comment]
Hi @shubhayu09 Welcome!

In addition to what quozl has said, you should also look at our [contributing guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md).

**Comment by quozl** [comment]
@shubhayu09, please review https://github.com/sugarlabs/www-sugarlabs/pull/354

**Comment by shubhayu09** [comment]
> @shubhayu09, please review #354

Yeah sure

**Comment by nikkuAg** [comment]
Hello,
Can I work on this issue?
I will also incorporate the changes for the icons in footer and side bar.

**Comment by quozl** [comment]
I'm tired of being asked.  It's about time you read our guide to [Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) in particular where it starts out saying

> "_Please note there is no need to ask permission to work on an issue. You should check for pull requests linked to an issue you are addressing; if there are none, then assume nobody has done anything. Begin to fix the problem, test, make your commits, push your commits, then make a pull request. Mention an issue number in the pull request, but not the commit message. These practices allow the competition of ideas (Sugar Labs is a meritocracy)._"

If your purpose is to block other contributors, such as @shubhayu09 here, that won't work.  We'll take whichever pull request is best, or even combine pull requests.  Let's get this done.

**Comment by nikkuAg** [comment]
Hey @quozl  @chimosky,

I want to confirm that is it required to use files like ionicons.min.css as there is an easier way by using a script and then importing the icons.

**Comment by chimosky** [comment]
Currently the idea is to update the existing `ionicons.min.css` version and that includes using the file, if you think there's a better way then you can open a PR and add why you think that's better to your commit message as it'll be easier for us to test and review and move the convo forward.

**Comment by quozl** [comment]
Sorry. I don't understand the question.  I agree with @chimosky that it would be clearer if we saw a pull request, which you can mark as draft if it is not intended for merging.  The issue here (https://github.com/sugarlabs/www-sugarlabs/issues/353) is that an old version is being used.  Removing it would fix it, as would updating it.  If removing it is proposed, I'd like to see reasons.

**Comment by nikkuAg** [comment]
Hey @quozl @chimosky,

I have updated the changes for this issue in PR #354.
Please review it.
