### ISSUE TITLE
mySlides error

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#358]
No impact, but Firefox reports

```
Uncaught TypeError: slides[(slideIndex - 1)] is undefined
    showSlides http://www.sugarlabs.org/:1019
    <anonymous> http://www.sugarlabs.org/:1006
www.sugarlabs.org:1019:9
```

https://github.com/sugarlabs/www-sugarlabs/blob/master/_includes/footer.html#L183

I can't see any element with a mySlides class.  Looking back into git commit history, it was removed in bfe3fc25e30bf5fd15d16d0acd3555e0068cea6e, so perhaps that patch was incomplete.

**Comment by S-kus** [comment]
@quozl I raised the pull request for it, Please review.
