### ISSUE TITLE
Source for XO Laptop In The Classroom Book

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#36]
Does anyone have a copy of the source files for http://etoysillinois.org/files/The-XO-Laptop-in-the-Classroom.pdf ? :)

**Comment by walterbender** [comment]
I will find a copy.

On Fri, Apr 22, 2016 at 8:22 PM, Dave Crossland <notifications@github.com>
wrote:

> Does anyone have a copy of the source files for
> http://etoysillinois.org/files/The-XO-Laptop-in-the-Classroom.pdf ? :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sugarlabs/www-sugarlabs/issues/36>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by davelab6** [comment]
Thank you Walter! :)

**Comment by walterbender** [comment]
https://wiki.sugarlabs.org/images/3/32/La-laptop-xo-en-el-aula.pdf

On Sat, Apr 23, 2016 at 9:06 AM, Walter Bender <walter.bender@gmail.com>
wrote:

> I will find a copy.
>
> On Fri, Apr 22, 2016 at 8:22 PM, Dave Crossland <notifications@github.com>
> wrote:
>
>> Does anyone have a copy of the source files for
>> http://etoysillinois.org/files/The-XO-Laptop-in-the-Classroom.pdf ? :)
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sugarlabs/www-sugarlabs/issues/36>
>>
>
>
>
> --
> Walter Bender
> Sugar Labs
> http://www.sugarlabs.org
> <http://www.sugarlabs.org>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by davelab6** [comment]
Spanish version is awesome!! :D

**Comment by davelab6** [comment]
@walterbender any luck finding the source for this?

**Comment by quozl** [comment]
Stale, closing.
