### ISSUE TITLE
It is Sugar Labs, not Sugarlabs

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/www-sugarlabs#360]
We should update the website wherever it uses Sugarlabs instead of Sugar Labs. For example, in https://github.com/sugarlabs/www-sugarlabs#readme Line 4 ```# [Sugarlabs](https://www.sugarlabs.org/)```

**Comment by S-kus** [comment]
@walterbender I found this in 3 files, Other places are links. Please review the pr.
