### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by ishubham21** [sugarlabs/www-sugarlabs#364]
In the website footer, under the 'Development' section, the link to 'IRC Channel' targets to `http://chat.sugarlabs.org:9090/` that is incorrect. I also tried using `http://chat.sugarlabs.org` if it works, but it didn't.

**Comment by chimosky** [comment]
Thanks for pointing that out, for now if you can change the link to our [matrix](https://matrix.to/#/#sugar:matrix.org) channel I'd appreciate it and merge. Thanks!

**Comment by ishubham21** [comment]
> Thanks for pointing that out, for now if you can change the link to our [matrix](https://matrix.to/#/#sugar:matrix.org) channel I'd appreciate it and merge. Thanks!

I'm on it

**Comment by ishubham21** [comment]
Made a PR - https://github.com/sugarlabs/www-sugarlabs/pull/365
