### ISSUE TITLE
Slow load due to CDN

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#366]
Page load using Firefox in developer tools console mode shows some resources are not used from our server; this creates external dependencies and additional domain name resolution time.

* [ ] https://code.jquery.com/jquery-2.2.4.min.js (https://github.com/sugarlabs/www-sugarlabs/issues/349),
* [ ] https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
* [ ] https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js

**Comment by ishubham21** [comment]
I'm on it.

**Comment by ishubham21** [comment]
How about I include minified versions of the files like `bootstrap.js` and `bootstrap.css` alongside addressing the issue?
