### ISSUE TITLE
"Footer icons" are overlapping with "contribute to website"

### ISSUE THREAD

**Issue by S-kus** [sugarlabs/www-sugarlabs#370]
Footer icons `div` is overlapping with `#contributor` and it's also getting left-aligned for different screen sizes i.e. not responsive in the correct manner. As shown below:

![Screenshot from 2022-02-05 20-09-35 (1)](https://user-images.githubusercontent.com/86892991/152646547-95b4524a-f288-4bd7-8258-b69456c075c8.png)

![Screenshot from 2022-02-05 20-09-39](https://user-images.githubusercontent.com/86892991/152646553-e7d8f8eb-fe4e-40ba-919e-09a76450d34a.png)

**Comment by Raeskaa** [comment]
hey can you center that "contribute to website" thing down the footer icons div @S-kus

**Comment by S-kus** [comment]
Hello @Raeskaa, Could you please review my pull request #371? I have corrected it.

**Comment by Raeskaa** [comment]
@S-kus Yeah sure!
