### ISSUE TITLE
Site not rendering on Firefox

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#374]
Merging https://github.com/sugarlabs/www-sugarlabs/pull/373 broke the site for Firefox, spinner stays in front of content, and console shows 
```
Uncaught TypeError: e.indexOf is not a function
    load jQuery
    <anonymous> http://www.sugarlabs.org/:63
[jquery.js:2:84932](http://www.sugarlabs.org/js/jquery.js)
Uncaught TypeError: e.indexOf is not a function
    load jQuery
    <anonymous> http://www.sugarlabs.org/js/waypoints.js:8
    <anonymous> http://www.sugarlabs.org/js/waypoints.js:8
    <anonymous> http://www.sugarlabs.org/js/waypoints.js:8
    <anonymous> http://www.sugarlabs.org/js/waypoints.js:8
```

**Comment by quozl** [comment]
Master branch has been reset to dbd8f2bec6bca8f77b1f8f8769fa65e37c294b08.

**Comment by quozl** [comment]
@nikkuAg, please fix and redo jQuery upgrade, and test on Firefox?

**Comment by aritroCoder** [comment]
Is this open? I can try to fix this issue

**Comment by chimosky** [comment]
Hey @aritroCoder feel free to work on the issue, you should also take a look at our [contributing guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md). 

Looking forward to your PR!

**Comment by aritroCoder** [comment]
Hello, I have installed `ruby `and `ruby bundler`, now  when I try to run `bundle install` I get  some kind of error( screenshot attached). I searched some stackoverflow articles but they did not exactly help
![image](https://user-images.githubusercontent.com/92646038/189523673-74e62f6b-f99c-4f49-8b2c-e63a89b7e645.png)
by the the I am running this in ubuntu if that helps in some way

**Comment by quozl** [comment]
That's an internet problem.  Diagnose why your computer cannot reach that URL.
