### ISSUE TITLE
Bug : Input field covers sugar labs logo on width 1215px - 1280px 

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [sugarlabs/www-sugarlabs#375]
The input field covers up the logo when rendered on width 1215px - 1280px 

![image](https://user-images.githubusercontent.com/95560057/180978136-03d72ae7-4ffb-42d4-b6b2-5122ecf2f776.png)

**Comment by prayatharth** [comment]
Hey There ! Can I try Fix it?

**Comment by chimosky** [comment]
Hey @prayatharth please feel free to open a PR with your fix, also take a look at our [contributing guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing) which has some helpful information. 

Looking forward to your PR!

**Comment by kartikjoshi267** [comment]
Hey there, I would like to fix this issue! Shall I go ahead?

**Comment by quozl** [comment]
Thanks.  As per previous response, please read our contributing guide
and make a pull request.
