### ISSUE TITLE
Write email mini-course

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#38]
In https://github.com/sugarlabs/www-sugarlabs/pull/33/files#r61170562 @samdroid-apps wrote,

> One idea that interests me is using an email mini-course. This could involve collecting emails on the home page. Then, we guide people through getting set up and deriving value Sugar. First, this would involve general emails about how sugar integrates with the classroom, and other topics to build a positive relationship and trust. Then, it is easier to ask for a time investment to download and try SoaS. They will also actually know what to do in SoaS. After that, we could do more!
> 
> One bit of software that we could use is https://www.mautic.org But probably the most important part of this is making up the emails.

https://copyhackers.com/2015/10/copywriting-formula/ has some good structures for these

**Comment by walterbender** [comment]
We should try to get some of the great Sugar teachers engaged. Rosamel from .UY, for example.

**Comment by davelab6** [comment]
Concretely, what does them being engaged mean?

**Comment by quozl** [comment]
Stale, closing.
