### ISSUE TITLE
Text is not readable in mobile phones

### ISSUE THREAD

**Issue by Chickisnak** [sugarlabs/www-sugarlabs#388]
![issue](https://user-images.githubusercontent.com/104713627/213843874-e3339db6-7855-4100-a2af-efdb47a90b07.png)

**Comment by Chickisnak** [comment]
**Should I start working on this ?**

**Comment by quozl** [comment]
Why would you _not_ work on a problem if you can?  See our [Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) page.  Also, please don't raise issues for something you already have a fix for; instead, create a pull request.

The text you took a snapshot of is in http://www.sugarlabs.org/about-us/

Please confirm that is the URL you are viewing?

It looks fine to me on a mobile phone.  What browser and version are you trying to use?

**Comment by Chickisnak** [comment]
![issue](https://user-images.githubusercontent.com/104713627/213861038-d5b04a19-88f1-456e-a84d-b9759c19e1cb.png)
 

There is little issue of responsiveness. if we open it on phone , there is scrollbar horizontally

**Comment by Chickisnak** [comment]
for little issues , no need to create issues
for that directly create pull request ....that's why i am closing this request

**Comment by quozl** [comment]
Can you answer my two questions?

I've looked again, there are no scrollbars shown on my phone.
