### ISSUE TITLE
Verify Facebook Account

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#41]
Making an issue to track this :)

**Comment by khanstark** [comment]
@davelab6 whats with the fb account?

**Comment by davelab6** [comment]
Its not yet verified

**Comment by davelab6** [comment]
BTW I have reached out to the owner of https://www.facebook.com/sugarlabs and they were not willing to transfer the username immediately, but said they would get back to me

**Comment by samswag** [comment]
The page is now verified

**Comment by davelab6** [comment]
NICE!!
