### ISSUE TITLE
Beautify /press/ and figure out how to limit to show only the last 10, then put the other "archives" on another page.

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www-sugarlabs#456]
Two things:

1. make the /press page look better
2. limit entries to "10 most recent" and put other pages on an archive -- if this is very difficult, let me know. It's not super important, I suppose.

**Comment by pikurasa** [comment]
> @pikurasa I would like to work on it.

Go ahead.

**Comment by therealharshit** [comment]
@pikurasa I am done with beautifying the press page.

**Comment by therealharshit** [comment]
@pikurasa i have raised a PR #474 please review.

**Comment by therealharshit** [comment]
This issue has been fixed.
