### ISSUE TITLE
Add a page measuring Sugar against the LF CII Best Practices

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#47]
https://github.com/linuxfoundation/cii-best-practices-badge

**Comment by walterbender** [comment]
Sound like another goal for 2016.

On Mon, May 16, 2016 at 12:33 PM, Dave Crossland <notifications@github.com>
wrote:

> https://github.com/linuxfoundation/cii-best-practices-badge
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sugarlabs/www-sugarlabs/issues/47>
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by davelab6** [comment]
Done

**Comment by quozl** [comment]
Stale, closing.
