### ISSUE TITLE
How to do Localization

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#48]
Since the majority of sugar users speak Spanish or other languages than English, we will need to localize the site from English to Spanish and others. 

Sadly, Jekyll doesn't support l10n well (although this might change in the future, per https://github.com/github/mentorships/issues/106) so there are 2 ways to do it that I can see:
1. Put all content in IETF language code directories, and develop a set of language-specific layout HTML files and try to keep them in sync by hand. 
2. Migrate to https://github.com/grow (which should be straight forward, I can do this) and has proper PO support (https://grow.io/docs/translations/)

**Comment by walterbender** [comment]
I don't know Jekyll or grow very well, but i18n is pretty fundamental for our audience. A proper PO solution  would seem to make the most sense.

**Comment by quozl** [comment]
Stale, closing.
