### ISSUE TITLE
Add testing docs install instructions

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#51]
Something like:

---

For testing v0.109 (development release) on Fedora 23, Fedora 24 or Fedora Rawhide, we have a COPR repository that you can install very quickly: 

https://copr.fedorainfracloud.org/coprs/samtoday/sugar

If you already have Sugar installed on F23+, to upgrade your sugar to .you can just run the following commands:

```
dnf copr enable samtoday/sugar;
dnf update;
```

To try out the cutting edge developer's versions, check out the [developer documentation](https://developer.sugarlabs.org)

**Comment by quozl** [comment]
no longer maintained.
