### ISSUE TITLE
Harvest old copy for new site

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/www-sugarlabs#56]
http://web.archive.org/*/https://www.sugarlabs.org has archived copies of previous generations of the website. 

In IAEP thread "Sugar Labs Vision Discussion in 6 hours", Sean suggested going over these to find useful copywriting that could be considered.

**Comment by samdroid-apps** [comment]
It is in here, see 4c7fb0a

**Comment by davelab6** [comment]
Does it go back to 2010?

**Comment by davelab6** [comment]
(Assigning to myself to close)

**Comment by samdroid-apps** [comment]
That is the 2010 site... It just got imported into git 5 years late.

**Comment by samswag** [comment]
I will close this issue as it isn't relevant anyone.
