### ISSUE TITLE
site redesign idea

### ISSUE THREAD

**Issue by technomoda** [sugarlabs/www-sugarlabs#62]
![sugarlabs](https://cloud.githubusercontent.com/assets/11223564/23415917/a752e734-fd95-11e6-879d-fe6bb8c505b7.png)

Hi! this is a redesign idea for the site project for Outreachy. Any tips or suggestions would be greatly appreciated. I'm also trying to get in contact with the mentors for this project, I've already joined the IRC channel (nicnkame: dalia)

**Comment by samswag** [comment]
Nice concept, but did you take a look at the structure of the idea on
www-sugarlabs. There are two recommended websites that we should draw
inspiration on. I also think that this one is similar to the current
website.

Thanks

Samson

**Comment by diaxdo** [comment]
Is there a color scheme to follow? I was using the colors from the previous site.

**Comment by samswag** [comment]
http://sugarizer.org/

https://learningequality.org/

http://haxe.org/

I think this will do, but we will still retain the white color.
