### ISSUE TITLE
IRC chat box doesn't work on Google Chrome

### ISSUE THREAD

**Issue by iamutkarshtiwari** [sugarlabs/www-sugarlabs#69]
@geekrypter The IRC chat box doesn't seem to load the contents on the Google Chrome (Version 62.0.3202.89) (Official Build) (64-bit) Mac- 
![screen shot 2017-11-08 at 6 08 24 pm](https://user-images.githubusercontent.com/6258810/32549620-26f21c62-c4b0-11e7-8b90-2b2c97784f58.png)

However it works perfectly fine on Safari (Version 11.0.1)  (12604.3.5.1.1) on Mac -
![screen shot 2017-11-08 at 6 08 28 pm](https://user-images.githubusercontent.com/6258810/32549655-4cd33c86-c4b0-11e7-9082-8f7e858cba58.png)
 

Here is the console log for your reference - https://gist.github.com/iamutkarshtiwari/ef6ca08383a16023655354f102230302

PS- I have added "WARNING" and "ERROR" tags in the gist for your ease.

**Comment by geekrypter** [comment]
@iamutkarshtiwari, I will look into the issue and get back to you soon :)
