### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by synicalsyntax** [sugarlabs/www-sugarlabs#71]
Noticed the following issues with the navbar on the website:

![screenshot at nov 28 11-06-18](https://user-images.githubusercontent.com/15116870/33339130-01f919d8-d42d-11e7-8f1d-fe6e13c445da.png)

* In the desktop view, the text links aren't vertically aligned and are slightly above the center of the navbar.

![screenshot at nov 28 11-07-32](https://user-images.githubusercontent.com/15116870/33339156-1acf4a4a-d42d-11e7-874f-56816728fc44.png)

* The menu icon in mobile view is located slightly vertically below the center of the navbar.

![screenshot at nov 28 11-09-58](https://user-images.githubusercontent.com/15116870/33339157-1af31286-d42d-11e7-987a-e6c639ee3747.png)

* The padding for the menu icon in tablet view is off; it should be slightly to the left and more vertically-aligned towards the center.

**Comment by samswag** [comment]
Please could you confirm what browser and device you used for testing? so we might get a better idea. But thanks for figuring this out.

**Comment by synicalsyntax** [comment]
All tested on Chrome Version 62.0.3202.94; pictures of screenshots are from Chrome Developer Tools (Toggle device toolbar) as well.

**Comment by samswag** [comment]
Thanks for the information.
