### ISSUE TITLE
Suggestion: Center the subscribe button and move the contributton to the bottom-right

### ISSUE THREAD

**Issue by aryamanverma** [sugarlabs/www-sugarlabs#72]
We can probably center the subscribe button and move the contribution button to the bottom-right for better view.

![image](https://user-images.githubusercontent.com/34020217/33340054-fad11588-d4a0-11e7-958e-ce8ac9be24fb.png)

**Comment by GeekyShiva** [comment]
Please send browser details as well for such reporting, would be helpful :)

**Comment by quozl** [comment]
My preference is for subscribe button to be left aligned to the same position as the text entry field, which it is in the screenshot.

**Comment by aryamanverma** [comment]
I'm using firefox quantum 57.0 x64 on Linux Mint 18.2 Cinnamon x64

**Comment by quozl** [comment]
The button is now centered and left aligned, because it is the same width as the text entry.
