### ISSUE TITLE
Bug: Not able to view nav-bar text on hovering

### ISSUE THREAD

**Issue by aryamanverma** [sugarlabs/www-sugarlabs#73]
When I hover over the collapsed navbar the highlighting is done in the same color as the text and thus text is not visible.
![image](https://user-images.githubusercontent.com/34020217/33340206-7e73c886-d4a1-11e7-9f22-e1526b40ae3d.png)

**Comment by aryamanverma** [comment]
I'm using firefox quantum 57.0 x64 on Linux Mint 18.2 Cinnamon x64

**Comment by amaaniqbal** [comment]
I guess I was involved in fixing this. But anyways I could not able to replicate this via Chrome Inspector on hover and so I suppose, it can be closed. 

Please have a look once @samswag @quozl .

**Comment by quozl** [comment]
Tested, seems fixed.  Firefox on Ubuntu 16.04 and iOS 12.x.
