### ISSUE TITLE
Not enough margin between Social Help and Join the Conversation sections

### ISSUE THREAD

**Issue by synicalsyntax** [sugarlabs/www-sugarlabs#75]
![screenshot at nov 28 11-07-00](https://user-images.githubusercontent.com/15116870/33341065-9c20fd3c-d432-11e7-976c-c88d66a8d16b.png)

![screenshot at nov 28 11-53-16](https://user-images.githubusercontent.com/15116870/33341190-0898ea74-d433-11e7-95bc-027c5619e044.png)

In desktop + tablet view, the two sections look way too cramped to be together, even though they share the same area.

The spacing inbetween them should be more similar to the one on mobile view:

![screenshot at nov 28 11-53-02](https://user-images.githubusercontent.com/15116870/33341271-475e975e-d433-11e7-88dc-335dfdcf3bd5.png)

**Comment by quozl** [comment]
As of now, 40fae48424ccae898243db517c59ba0ebb61ca61, the spacing problem is already fixed on desktop and mobile views.
