### ISSUE TITLE
Change colors for social icons

### ISSUE THREAD

**Issue by ghost** [sugarlabs/www-sugarlabs#79]
### Instagram hover color
The social buttons on every page have it to where it will darken on hover. The Instagram icon doesn't. This can be fixed by making the gradient background be darker on hover.

I won't include which colors it should darken to because you guys will probably want different colors.

### Instagram color
The current colors for the Instagram icon don't look exactly like the real colors.

### GitHub color
The GitHub icon could be `#000` because it is always like that.

**Comment by samswag** [comment]
"The current colors for the Instagram icon don't look exactly like the real colors."

can you explain this line?

**Comment by CameronSamuels** [comment]
See how the first image (Sugarlab's) looks different. The top of it is darker purple where it should be lighter blue.

Sugarlab's: <img src="https://user-images.githubusercontent.com/25394678/33344871-02477a06-d450-11e7-9d98-818ab7d7ed64.png" width="64">
Example 1: <img src="https://user-images.githubusercontent.com/25394678/33344872-025a2110-d450-11e7-8616-3a9a66245afc.png" width="64">
Example 2: <img src="https://user-images.githubusercontent.com/25394678/33344874-027a1452-d450-11e7-8a0e-b64b6a093465.png" width="64">

**Comment by samswag** [comment]
This is the technology we are using http://socialsharekit.com/, could you make research around it, showing how it can be implemented on the socialsharekit

**Comment by CameronSamuels** [comment]
The code for the Social Share Kit is in [assets/dist/css/social-share-kit.css](https://github.com/sugarlabs/www-sugarlabs/blob/master/assets/dist/css/social-share-kit.css). You can modify this file to update the social icons.

### GitHub
Adding the following to the end of the file will make the GitHub icon be black:
```css
.ssk-github {
    background: #000
}
```
\*You can add `!important` to the property if this code is above code that will override it.
\**This will make the GitHub icon lighten on hover (which actually looks nice, but also can't be avoided when making it black)

### Instagram
At the end of the file, there is `.instagram_colour` and `.instagram_colour:hover`. Editing them can improve the gradient background of the image.

\*The `.instagram_colour:hover` doesn't do anything and should be removed to improve load time and data usage. Other css styles could also be removed unless being used or used in the future.

**Comment by samswag** [comment]
Thanks, for the insight.

**Comment by Oluebube** [comment]
![1620013-48](https://user-images.githubusercontent.com/26440633/35525358-8c0c6dc8-0524-11e8-923a-c84086984e78.png)
How about something like this?

**Comment by cameronsamuels** [comment]
Sorry for the late response.

I do like that color a lot, even though it isn't the real icon background.

You could still use it, because I know it was really hard to do that exact thing before, so that could still work.

But it's all up to you.

**Comment by IfeanyiEkperi** [comment]
The Instagram icon doesn't still look great, the color is still not same, the hover makes it worse. It's better without a background and then a hover over color of red or blue.

**Comment by quozl** [comment]
Seems okay now.  I don't think hover colour changes are helpful, but they are present.
