### ISSUE TITLE
video with its code on line 51 of index.html does not play

### ISSUE THREAD

**Issue by madewithkode** [sugarlabs/www-sugarlabs#82]
The video with its code on line 51 does not play. this was tested on both chrome and firefox browsers.

a look on the  code shows that there is a problem with the placement of the  `#<video>` end tag.  
nice work sugarlabs!

**Comment by abdulsamad234** [comment]
I think the problem is in the source of the video. The link provided in the source gives a 404 error (not found).

**Comment by GeekyShiva** [comment]
this should be put for gci @abdulsamad234

**Comment by abdulsamad234** [comment]
We're working on it @GeekyShiva

**Comment by GeekyShiva** [comment]
👍
