### ISSUE TITLE
IRC chat box is clipped of with no availability of scroll bar

### ISSUE THREAD

**Issue by aryamanverma** [sugarlabs/www-sugarlabs#83]
I'm on firefox quantum 57.0 x64 on Linux Mint 18.2 Cinnamon desktop x64
![image](https://user-images.githubusercontent.com/34020217/33357415-fae1c544-d4e7-11e7-828f-fda52d71fcab.png)

**Comment by Hrishi1999** [comment]
Can not reproduce on my phone. Seems fine by default.

**Comment by aryamanverma** [comment]
This happens when you resize the window to a smaller scale (I've tested on desktop only) there's scroll bar on the website but not on the IRC box.

**Comment by amaaniqbal** [comment]
We are not having IRC on our website for now. So I suppose this can be closed. Your reviews @quozl?

**Comment by quozl** [comment]
IRC was disabled anyway because it was not working, due to new security restrictions and out of date JavaScript component.
