### ISSUE TITLE
IRC Chat Disconnects When You Change Pages

### ISSUE THREAD

**Issue by ad591964** [sugarlabs/www-sugarlabs#87]
Suggestion: Make it so that you can keep the IRC channel is still available when you try to access a new page.
![image](https://user-images.githubusercontent.com/22689094/33401913-91f6bc68-d520-11e7-89bd-85ff7ff6f4f1.png)

Also, on Chrome Version 62.0.3202.94, when you try to go to a new page and the IRC chat is open, the "Do you want to leave this site" pops up. It would be nice to just go to the next page without having to hit "leave."

![image](https://user-images.githubusercontent.com/22689094/33401905-8e509c00-d520-11e7-8f62-5808ced2e39b.png)

IRC Chat disconnects when you leave the current page as shown.
![image](https://user-images.githubusercontent.com/22689094/33401956-b26b0846-d520-11e7-86cb-275c1116dacd.png)

**Comment by abdulsamad234** [comment]
Do you have any suggestions as to how these could be solved?

**Comment by amaaniqbal** [comment]
We are not having IRC on our website for now. So I suppose this can be closed. Any reviews @quozl?
