### ISSUE TITLE
Suggestion: Having the search button open a text field

### ISSUE THREAD

**Issue by kipply** [sugarlabs/www-sugarlabs#89]
At the moment, the search button in the navigation leads to a page. Having a text field appear would make more sense as it lets people reference their current page to remember what it is they may be searching for. Hitting the search again would then lead to a page of results.

**Comment by abdulsamad234** [comment]
great idea

**Comment by samswag** [comment]
Can you give me and example of that you are saying, like a website?

**Comment by kipply** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/13735595/33435924-7f38e6be-d5b1-11e7-9133-0a112f7d8fa6.png">
[Medium](https://medium.com/) does it
