### ISSUE TITLE
Calculator App in Try Now is Broken When Trying to Do Trig

### ISSUE THREAD

**Issue by ad591964** [sugarlabs/www-sugarlabs#90]
When you try to do Arc Trig in deg mode as shown below, you get some really weird answers.
![image](https://user-images.githubusercontent.com/22689094/33405740-30c8bbf8-d52f-11e7-93cc-092cfdb511b1.png)
acos(0) should be 90 degrees.
asin(1) should be 90 degrees. 
acos(1) should be 0 degrees. 
atan(1) should be 45 degrees.
Instead of these, the calculator gave me a whole bunch of wrong answers and one (acos(0)) that would be right if it was in radians.

**Comment by quozl** [comment]
That's not part of the site.

See [Calculate.activity](https://github.com/llaske/sugarizer/tree/master/activities/Calculate.activity) for the source and issue tracking.

**Comment by CameronSamuels** [comment]
@ad591964, the calculator is not wrong, it's just showing radians (1.57rad = 90deg). And when doing arc trig, computers return radians and not degrees.

This issue could actually be something different: choice for degrees or radians.
