### ISSUE TITLE
Suggestion: Footer would look nicer, if content would be in center.

### ISSUE THREAD

**Issue by sanatankc** [sugarlabs/www-sugarlabs#92]
This is how Footer looks like now:

![www sugarlabs org_](https://user-images.githubusercontent.com/20373641/33427733-5ffe73be-d5ec-11e7-941e-bd8b4c5511ae.png)

This is how I think Footer should look like:

![www sugarlabs org_ 1](https://user-images.githubusercontent.com/20373641/33427759-795c63d4-d5ec-11e7-8194-d8d364b375ea.png)

I can send a pull related to this, if it's ok. 😃

**Comment by samswag** [comment]
What device is this? a > 7inch device? i am assuming is a tablet right?

**Comment by sanatankc** [comment]
Yes.

**Comment by sanatankc** [comment]
Same goes for mobile screen.

**Comment by samswag** [comment]
Send a PR?, lets look into it.

**Comment by sanatankc** [comment]
I was looking through files in repo. I kind of figured out where to make changes. But I don't know if project auto-compiles on save or not because when I made changes in one of the sass file (`main.sass`), It did't reflect changes into site or `airspace.css`
