### ISSUE TITLE
Suggestion for social icons

### ISSUE THREAD

**Issue by sdushantha** [sugarlabs/www-sugarlabs#93]
Would be nice if the Instagram social icon would a single color because the other icons have a single color

**Comment by samswag** [comment]
See this.... Then tell me what you think.

https://www.google.com.ng/search?q=instagram+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiBtJCZn-bXAhUqLcAKHf3wD1cQ_AUICigB&biw=1280&bih=726

**Comment by sdushantha** [comment]
@samswag I know thats the color of the Instagram logo. But it kinda stands out from the other icons. If you want, you could use one of the colors of the Instagram logo so that it matches with the other icons

**Comment by IfeanyiEkperi** [comment]
@sdushantha You have a point but that doesn't make it look professional. Instagram should be represented by it's colors.
