### ISSUE TITLE
Navbar looks ugly after scrolling down.

### ISSUE THREAD

**Issue by artur9010** [sugarlabs/www-sugarlabs#95]
![image](https://user-images.githubusercontent.com/4835677/33434079-6d481f2e-d5de-11e7-84c9-d37bda091533.png)

After adding 3px to padding it looks better. (but not ideal :/)

![image](https://user-images.githubusercontent.com/4835677/33434179-c2483a0e-d5de-11e7-8b50-ec084767fcb1.png)

Windows 7, Chrome 62.0.3202.94 (Official Build) (64-bit)
1920x1080

---
(Google Code-In task - artur@motyka.pro)

**Comment by kipply** [comment]
Note that an issue for this problem already exists! #71 
Should probably be fixed with vertical centering.
