### ISSUE TITLE
Blog Section Is not Mobile Friendly. Social Media Links

### ISSUE THREAD

**Issue by ashishkamathi** [sugarlabs/www-sugarlabs#97]
The Blog Archive section at planet.sugarlabs.org is not mobile friendly this makes it look unattractive. Moreover, I think that in the traditional desktop version the social media links that hover at the left should be placed below because they seem to be sort of irritative.

Google code-in Entry: ashishkamathi7@gmail.com
![as](https://user-images.githubusercontent.com/32205608/33437662-a859f44a-d60e-11e7-8c1a-1da6bccd2961.png)

**Comment by S-kus** [comment]
@quozl I would like to work on this. But I am not able to find the codebase for this.

**Comment by quozl** [comment]
It is not part of this repository.  I don't know either, but it shouldn't be too hard.  Ask on our mailing list, and check the Wiki for pages that refer to the infrastructure service planet.sugarlabs.org.

**Comment by S-kus** [comment]
Do I need to mail at  sugar-devel@lists.sugarlabs.org? I got it from page https://lists.sugarlabs.org/listinfo/sugar-devel.

**Comment by chimosky** [comment]
> Do I need to mail at [sugar-devel@lists.sugarlabs.org](mailto:sugar-devel@lists.sugarlabs.org)? I got it from page https://lists.sugarlabs.org/listinfo/sugar-devel.

Yes that's the sugar-devel mailing list.
