### ISSUE TITLE
Social Media Suggestions

### ISSUE THREAD

**Issue by ashishkamathi** [sugarlabs/www-sugarlabs#98]
I think you can change your Instagram account to business profile so that you may reach a larger audience and can also improve the youtube section so as to make it attractive. You can properly align the background image. 

Google code-in entry: ashishkamathi7@gmail.com

**Comment by samswag** [comment]
Thanks we are working on it.

**Comment by octamois** [comment]
@samswag , i think it's completed and this can be closed
